// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Dicyanin Labs
//! The relay's call codec checked against the client's, byte for byte.
//!
//! Two independently written codecs that were never compared are two bugs
//! waiting, and the failure is quiet in exactly the wrong way: a field width that
//! drifted by one byte makes every frame of that tag undecodable by the other
//! side, and what a user sees is a call that connects and is silent.
//!
//! So `specs/backend/contracts/wire/vectors/call-frames.json` is generated by the
//! **client**, by `scripts/call-vectors.sh`, which compiles
//! `Sources/WealdRelayNetworking`. This suite asserts the relay reproduces every
//! byte of every case, and that it reads its own encoding back to the same
//! fields. A Rust test asserting against a Rust-generated value would prove
//! nothing at all, which is the argument `tests/vectors.rs` and
//! `tests/access_vectors.rs` already make for their own formats.

use std::path::PathBuf;

use wealdrelay::calls::{CallKind, MAX_CALL_BODY_BYTES, MAX_MEDIA_CT_BYTES};
use wealdrelay::frame::{Frame, FrameTag, PROTOCOL_VERSION};

fn vectors_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../specs/backend/contracts/wire/vectors/call-frames.json")
}

fn hex_to_bytes(text: &str) -> Vec<u8> {
    assert!(
        text.len().is_multiple_of(2),
        "hex must be whole bytes: {text}"
    );
    (0..text.len())
        .step_by(2)
        .map(|index| u8::from_str_radix(&text[index..index + 2], 16).expect("hex"))
        .collect()
}

fn to_hex(bytes: &[u8]) -> String {
    bytes.iter().map(|byte| format!("{byte:02x}")).collect()
}

/// `"deadbeef"`, or `"fill:5a:4096"` for the long payloads, which the vector file
/// writes in that form so a human can read it.
fn payload(text: &str) -> Vec<u8> {
    match text.strip_prefix("fill:") {
        Some(rest) => {
            let (byte, count) = rest.split_once(':').expect("fill:BB:N");
            let byte = u8::from_str_radix(byte, 16).expect("a hex byte");
            let count: usize = count.parse().expect("a count");
            vec![byte; count]
        }
        None => hex_to_bytes(text),
    }
}

fn document() -> serde_json::Value {
    let text = std::fs::read_to_string(vectors_path()).expect(
        "the vector file must be checked in; regenerate it with scripts/call-vectors.sh --write",
    );
    serde_json::from_str(&text).expect("valid json")
}

/// Rebuild one case's frame from its `fields`, which are written out in the
/// vector file rather than reflected from either type. Building from the fields
/// rather than from `encoded` is the point: if the relay's encoder is right, the
/// two agree; nothing here is derived from the bytes under test.
fn frame_of(case: &serde_json::Value) -> Frame {
    let fields = &case["fields"];
    let tag = case["tag"].as_u64().expect("a tag");
    let call_id = hex_to_bytes(fields["call_id"].as_str().expect("call_id"));
    match u16::try_from(tag).ok().and_then(FrameTag::from_u16) {
        Some(FrameTag::Call) => Frame::Call {
            call_id,
            group: hex_to_bytes(fields["group"].as_str().expect("group")),
            epoch: fields["epoch"].as_u64().expect("epoch"),
            kind: u8::try_from(fields["kind"].as_u64().expect("kind")).expect("a small kind"),
            body: payload(fields["body"].as_str().expect("body")),
        },
        Some(FrameTag::Media) => Frame::Media {
            call_id,
            stream: hex_to_bytes(fields["stream"].as_str().expect("stream")),
            seq: fields["seq"].as_u64().expect("seq"),
            ct: payload(fields["ct"].as_str().expect("ct")),
        },
        other => panic!("a call vector carried tag {tag:?}, which is {other:?}"),
    }
}

#[test]
fn the_relay_reproduces_every_byte_the_client_encoded() {
    let document = document();
    let cases = document["cases"].as_array().expect("a cases array");
    assert!(
        cases.len() >= 8,
        "the corpus lost cases: {} left, and a shrinking corpus is how a wire test stops testing",
        cases.len()
    );
    for case in cases {
        let id = case["id"].as_str().expect("an id");
        let expected = case["encoded"].as_str().expect("encoded bytes");
        let produced = to_hex(&frame_of(case).encode());
        assert_eq!(
            produced, expected,
            "{id}: the relay and the client encode this frame differently"
        );
    }
}

#[test]
fn the_relay_decodes_every_vector_back_to_the_fields_it_names() {
    // The other direction, and it is not the same claim. An encoder and a decoder
    // that are wrong in the same way round trip perfectly against themselves; what
    // catches that is decoding bytes this side did not produce.
    for case in document()["cases"].as_array().expect("a cases array") {
        let id = case["id"].as_str().expect("an id");
        let bytes = hex_to_bytes(case["encoded"].as_str().expect("encoded bytes"));
        let decoded = Frame::decode(&bytes).unwrap_or_else(|error| {
            panic!("{id}: the relay could not read the client's bytes: {error}")
        });
        assert_eq!(decoded, frame_of(case), "{id}: decoded to the wrong fields");
    }
}

#[test]
fn both_sides_agree_on_the_version_and_the_two_ceilings() {
    // The numbers the frames are meaningless without. A client that thought the
    // media ceiling was 1600 would send frames the relay refuses, and the refusal
    // would look like a network fault rather than like a disagreement.
    let document = document();
    // A range rather than an equality, and the reason is the same one `CONNECT`'s
    // decoder gives for admitting a version below this build's maximum. This corpus
    // records the version it was generated at, and version 4 (`WAKE`,
    // `specs/backend/relay/push.md`) added a frame without touching either call frame
    // or the envelope. Pinning equality here would mean regenerating a corpus that has
    // not changed every time an unrelated frame is added, and a regenerated corpus is
    // one nobody re-derives by hand.
    let generated_at = document["protocol_version"]
        .as_u64()
        .expect("the corpus records the version it was generated at");
    assert!(
        (u64::from(wealdrelay::calls::CALL_PROTOCOL_VERSION)..=u64::from(PROTOCOL_VERSION))
            .contains(&generated_at),
        "the corpus was generated at version {generated_at}, which is either older than the \
         version that introduced these frames or newer than this build speaks"
    );
    assert_eq!(
        document["call_protocol_version"].as_u64(),
        Some(u64::from(wealdrelay::calls::CALL_PROTOCOL_VERSION))
    );
    assert_eq!(
        document["max_call_body_bytes"].as_u64(),
        Some(MAX_CALL_BODY_BYTES as u64)
    );
    assert_eq!(
        document["max_media_ct_bytes"].as_u64(),
        Some(MAX_MEDIA_CT_BYTES as u64)
    );
}

#[test]
fn the_corpus_covers_every_signalling_kind() {
    // Coverage of the closed set, checked against the set rather than against a
    // number. A kind added to `CallKind` with no vector is a routing decision no
    // cross-language test has ever exercised.
    let document = document();
    let kinds: Vec<u64> = document["cases"]
        .as_array()
        .expect("a cases array")
        .iter()
        .filter(|case| case["tag"].as_u64() == Some(FrameTag::Call as u64))
        .filter_map(|case| case["fields"]["kind"].as_u64())
        .collect();
    for kind in CallKind::ALL {
        assert!(
            kinds.contains(&u64::from(*kind as u8)),
            "no vector carries kind {} ({})",
            *kind as u8,
            kind.as_str()
        );
    }
}
