// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Dicyanin Labs
//! The one-time code's hash, generated here for the client to check itself against.
//!
//! This runs the opposite way from `access_vectors.rs`, and deliberately. There the
//! vectors are generated by the client and asserted by the relay, because the client's
//! encoder was the one that already existed and the relay's was the new one. Here it is
//! reversed: the reference implementation is the `argon2` crate this relay verifies
//! codes with, and the new implementation is `Sources/Invite/Argon2id.swift`, a
//! hand-written port that exists because macOS has no Argon2 and the invite issuer has
//! to compute exactly the hash this relay will compare against.
//!
//! So the authority is Rust, the file is generated here, and
//! `Tests/InviteCodeVectorTests.swift` asserts the Swift port reproduces it. A Swift
//! test asserting against a Swift-generated value would prove only that Swift is
//! self-consistent, which is not the claim: the claim is that an invite issued on a Mac
//! is redeemable against this binary.
//!
//! Regenerate with `WEALD_WRITE_VECTORS=1 cargo test --test invite_code_vectors`.
//! Without that variable the test asserts the checked-in file still matches, so a
//! change to either the parameters or the alphabet fails on the side that did not
//! change.

use std::path::PathBuf;

use wealdrelay::invite::code::{self, Code};

fn vectors_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../specs/backend/contracts/wire/vectors/invite-code.json")
}

fn to_hex(bytes: &[u8]) -> String {
    bytes.iter().map(|byte| format!("{byte:02x}")).collect()
}

/// The cases, chosen for the edges rather than for coverage of the middle.
///
/// All zero and all one bits are the two values a shift or a mask bug produces; the
/// third is an arbitrary value whose symbols span the alphabet. Each is hashed against
/// two salts, because the salt is the token and a hash that ignored it would still pass
/// a single-salt suite.
fn cases() -> Vec<(u64, [u8; 16])> {
    vec![
        (0, [0u8; 16]),
        (0x0fff_ffff_ffff_ffff, [0xffu8; 16]),
        (
            0x0123_4567_89ab_cdef,
            [
                0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99, 0xaa, 0xbb, 0xcc, 0xdd,
                0xee, 0xff,
            ],
        ),
    ]
}

#[test]
fn code_hash_vectors() {
    let generated: Vec<serde_json::Value> = cases()
        .into_iter()
        .map(|(bits, token)| {
            let code = Code::from_bits(bits);
            serde_json::json!({
                "bits": bits,
                "symbols": code.symbols(),
                "grouped": code.grouped(),
                "token": to_hex(&token),
                "hash": to_hex(&code::hash_token(code, &token)),
            })
        })
        .collect();

    let document = serde_json::json!({
        "note": "Argon2id of an invite's one-time code, salted with its token. \
                 Generated by backend/wealdrelay/tests/invite_code_vectors.rs and \
                 asserted by Tests/InviteCodeVectorTests.swift.",
        "memory_kib": code::MEMORY_KIB,
        "iterations": code::ITERATIONS,
        "lanes": code::LANES,
        "alphabet": String::from_utf8_lossy(code::ALPHABET),
        "cases": generated,
    });

    let rendered = serde_json::to_string_pretty(&document).expect("serialise") + "\n";
    if std::env::var("WEALD_WRITE_VECTORS").is_ok() {
        std::fs::create_dir_all(vectors_path().parent().expect("parent")).expect("mkdir");
        std::fs::write(vectors_path(), &rendered).expect("write vectors");
        return;
    }
    let existing = std::fs::read_to_string(vectors_path()).expect(
        "specs/backend/contracts/wire/vectors/invite-code.json is missing. \
         Regenerate with WEALD_WRITE_VECTORS=1 cargo test --test invite_code_vectors",
    );
    assert_eq!(
        existing, rendered,
        "the checked-in code vectors no longer match what this relay computes"
    );
}

/// Crockford's remappings, asserted here as well as in `invite_code.rs`, because the
/// client parses codes people retype and the two parsers have to agree about what a
/// code even is before a hash can be compared.
#[test]
fn crockford_remappings_round_trip() {
    let code = Code::from_bits(0x0123_4567_89ab_cdef);
    let typed = code
        .grouped()
        .to_lowercase()
        .replace('1', "l")
        .replace('0', "o");
    assert_eq!(Code::parse(&typed).expect("parses"), code);
    // `U` is excluded on purpose and is never remapped: accepting it would give one
    // code two spellings.
    assert!(Code::parse("UUUU-UUUU-UUUU").is_err());
}
