// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Dicyanin Labs
//! The relay's `BLOB` request codec checked against the client's, byte for byte.
//!
//! Two independently written codecs that were never compared are two bugs waiting,
//! and this pair bit twice: every `media-put` against the hosted relay was answered
//! `reject/malformed_header` (WEALD-L333, then WEALD-L336 on a binary built after
//! L333 was closed). That refusal is raised at one line, the `Request::decode`
//! failure arm in `media/mod.rs`, and it names no field, so nothing on either side
//! could say whether the client's bytes were wrong, this decoder was wrong, or the
//! running image predated both.
//!
//! So `specs/backend/contracts/wire/vectors/media-requests.json` is generated by
//! the **client**, by `scripts/media-vectors.sh`, which compiles
//! `Sources/Sync/MediaWire.swift`. This suite asserts the relay reads every byte of
//! every case and re-encodes it identically. A Rust test asserting against a
//! Rust-generated value would prove nothing at all, which is the argument
//! `tests/call_vectors.rs`, `tests/vectors.rs` and `tests/access_vectors.rs`
//! already make for their own formats.

use std::path::PathBuf;

use wealdrelay::media::wire::{Request, MAX_LIST};

fn vectors_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../specs/backend/contracts/wire/vectors/media-requests.json")
}

fn hex_to_bytes(text: &str) -> Vec<u8> {
    assert!(
        text.len().is_multiple_of(2),
        "hex must be whole bytes: {text}"
    );
    (0..text.len())
        .step_by(2)
        .map(|index| u8::from_str_radix(&text[index..index + 2], 16).expect("hex"))
        .collect()
}

fn to_hex(bytes: &[u8]) -> String {
    bytes.iter().map(|byte| format!("{byte:02x}")).collect()
}

fn document() -> serde_json::Value {
    let text = std::fs::read_to_string(vectors_path()).expect(
        "the vector file must be checked in; regenerate it with scripts/media-vectors.sh --write",
    );
    serde_json::from_str(&text).expect("valid json")
}

/// Rebuild one case's request from its `fields`, which are written out in the
/// vector file rather than reflected from either type. Building from the fields
/// rather than from `encoded` is the point: if this decoder is right, the two
/// agree, and nothing here is derived from the bytes under test.
fn request_of(case: &serde_json::Value) -> Request {
    let fields = &case["fields"];
    let tag = case["tag"].as_u64().expect("a tag");
    match tag {
        1 => Request::Put {
            workspace: hex_to_bytes(fields["workspace"].as_str().expect("workspace")),
            group: hex_to_bytes(fields["group"].as_str().expect("group")),
            hash: hex_to_bytes(fields["hash"].as_str().expect("hash")),
            ciphertext_len: fields["ciphertext_len"].as_u64().expect("ciphertext_len"),
        },
        2 => Request::Get {
            workspace: hex_to_bytes(fields["workspace"].as_str().expect("workspace")),
            group: hex_to_bytes(fields["group"].as_str().expect("group")),
            hash: hex_to_bytes(fields["hash"].as_str().expect("hash")),
        },
        3 => Request::MultipartPart {
            session_id: hex_to_bytes(fields["session_id"].as_str().expect("session_id")),
            part_number: u32::try_from(fields["part_number"].as_u64().expect("part_number"))
                .expect("a 32 bit part number"),
            expected_len: fields["expected_len"].as_u64().expect("expected_len"),
        },
        4 => Request::MultipartComplete {
            session_id: hex_to_bytes(fields["session_id"].as_str().expect("session_id")),
            parts: fields["parts"]
                .as_array()
                .expect("a parts array")
                .iter()
                .map(|part| {
                    let pair = part.as_array().expect("a [number, etag] pair");
                    (
                        u32::try_from(pair[0].as_u64().expect("a part number"))
                            .expect("a 32 bit part number"),
                        hex_to_bytes(pair[1].as_str().expect("an etag")),
                    )
                })
                .collect(),
        },
        5 => Request::MultipartAbort {
            session_id: hex_to_bytes(fields["session_id"].as_str().expect("session_id")),
        },
        10 => Request::List {
            workspace: hex_to_bytes(fields["workspace"].as_str().expect("workspace")),
            group: hex_to_bytes(fields["group"].as_str().expect("group")),
        },
        13 => Request::Quota {
            group: hex_to_bytes(fields["group"].as_str().expect("group")),
        },
        other => panic!("a media vector carried tag {other}, which this build does not know"),
    }
}

#[test]
fn the_relay_reads_every_byte_the_client_encoded() {
    // The direction that matters for the live failure: these are the exact bytes
    // `media-put` writes, and a relay that answers `malformed_header` to one of them
    // is a relay that cannot carry a file at all.
    let document = document();
    let cases = document["cases"].as_array().expect("a cases array");
    assert!(
        cases.len() >= 10,
        "the corpus lost cases: {} left, and a shrinking corpus is how a wire test stops testing",
        cases.len()
    );
    for case in cases {
        let id = case["id"].as_str().expect("an id");
        let bytes = hex_to_bytes(case["encoded"].as_str().expect("encoded bytes"));
        let decoded = Request::decode(&bytes).unwrap_or_else(|error| {
            panic!("{id}: the relay could not read the client's bytes: {error:?}")
        });
        assert_eq!(
            decoded,
            request_of(case),
            "{id}: decoded to the wrong fields"
        );
    }
}

#[test]
fn the_relay_reproduces_every_byte_the_client_encoded() {
    // The other direction, and it is not the same claim. A decoder that is lenient in
    // the wrong place reads bytes it should refuse and would pass the test above; what
    // catches that is re-encoding the fields and comparing the hex.
    for case in document()["cases"].as_array().expect("a cases array") {
        let id = case["id"].as_str().expect("an id");
        let expected = case["encoded"].as_str().expect("encoded bytes");
        assert_eq!(
            to_hex(&request_of(case).encode()),
            expected,
            "{id}: the relay and the client encode this request differently"
        );
    }
}

#[test]
fn the_corpus_covers_every_request_tag_the_transfer_path_uses() {
    // Coverage against the set rather than a count. A tag with no vector is a decode
    // no cross-language test has ever exercised, which is how L333 stayed open: the
    // put header was reasoned about on paper and never compared.
    let document = document();
    let tags: Vec<u64> = document["cases"]
        .as_array()
        .expect("a cases array")
        .iter()
        .filter_map(|case| case["tag"].as_u64())
        .collect();
    for tag in [1, 2, 3, 4, 5, 10, 13] {
        assert!(tags.contains(&tag), "no vector carries request tag {tag}");
    }
}

#[test]
fn both_sides_agree_on_the_list_ceiling() {
    // The number the corpus is meaningless without: a client that thought the list
    // bound was larger would send a completion the relay refuses, and the refusal
    // would read as a broken upload rather than as a disagreement.
    assert_eq!(document()["max_entries"].as_u64(), Some(MAX_LIST as u64));
}
