// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Dicyanin Labs
//! The relay's `WAKE` codec against the corpus computed from the CDDL.
//!
//! `specs/backend/contracts/wire/vectors/push-frames.json` is computed by hand from
//! the `WakeFrame` production in `../wire.cddl`, by neither implementation's
//! encoder. That is the whole value of it: a corpus generated by a side under test
//! proves the two halves of one program agree with each other, which they always do.
//! This suite asserts the relay reproduces every accepted case byte for byte, reads
//! every one of them back to the fields the file names, and refuses every case the
//! file says is a refusal.
//!
//! ## Nothing is skipped
//!
//! Every vector is walked. A case whose shape this file does not recognise is a
//! failure rather than a `continue`, because a corpus that silently ignores what it
//! does not understand is a corpus that stops testing the day somebody adds a field.
//! The one thing read defensively is the file's own layout: `name`, `form`, `hex`,
//! `expect` and `reason` are the keys this suite depends on, and it says so when one
//! is missing rather than unwrapping into a panic nobody can read.
//!
//! ## Where a refusal happens
//!
//! Two refusals in the corpus are not the codec's and cannot be. An expiry already
//! in the past is a judgement against the relay's own clock, which the codec does not
//! have, so that case is driven through `Session` in `Ready`. Everything else is
//! refused by `Frame::decode`, which is where a hostile peer's bytes meet this build.

use std::path::PathBuf;

use wealdrelay::config::{keys, Config, Values};
use wealdrelay::frame::{ErrorClass, ErrorCode, Frame, FrameTag, WakeBody, PROTOCOL_VERSION};
use wealdrelay::session::{Reaction, Session};

fn vectors_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../specs/backend/contracts/wire/vectors/push-frames.json")
}

fn document() -> serde_json::Value {
    let text = std::fs::read_to_string(vectors_path()).expect(
        "specs/backend/contracts/wire/vectors/push-frames.json must be checked in: it is the \
         only cross-implementation check on the WAKE codec, and a wire format with no corpus \
         is a wire format two builds disagree about quietly",
    );
    serde_json::from_str(&text).expect("valid json")
}

/// The vectors, as a list this file can walk without unwrapping into a panic.
fn vectors(document: &serde_json::Value) -> Vec<Vector> {
    let raw = document["vectors"]
        .as_array()
        .expect("the file carries a `vectors` array");
    assert!(
        raw.len() >= 12,
        "the corpus lost cases: {} left, and a shrinking corpus is how a wire test stops testing",
        raw.len()
    );
    raw.iter()
        .enumerate()
        .map(|(index, case)| Vector::read(index, case))
        .collect()
}

/// One case, in the four fields this suite depends on.
#[derive(Debug)]
struct Vector {
    name: String,
    form: u8,
    bytes: Vec<u8>,
    accepted: bool,
    /// The qualified code the file names, when it names one. Absent on the accepted
    /// cases, which have nothing to be refused with.
    code: Option<String>,
    reason: String,
}

impl Vector {
    fn read(index: usize, case: &serde_json::Value) -> Self {
        let name = case["name"]
            .as_str()
            .unwrap_or_else(|| panic!("vector {index} has no `name`"))
            .to_string();
        let form = case["form"]
            .as_u64()
            .and_then(|value| u8::try_from(value).ok())
            .unwrap_or_else(|| panic!("{name}: `form` is missing or is not a small integer"));
        let hex = case["hex"]
            .as_str()
            .unwrap_or_else(|| panic!("{name}: `hex` is missing"));
        let expect = case["expect"]
            .as_str()
            .unwrap_or_else(|| panic!("{name}: `expect` is missing"));
        let accepted = match expect {
            "accept" => true,
            "reject" => false,
            other => panic!("{name}: `expect` is {other}, which is neither accept nor reject"),
        };
        Self {
            name,
            form,
            bytes: hex_to_bytes(hex),
            accepted,
            code: case["code"].as_str().map(str::to_string),
            reason: case["reason"]
                .as_str()
                .or_else(|| case["note"].as_str())
                .unwrap_or("")
                .to_string(),
        }
    }
}

fn hex_to_bytes(text: &str) -> Vec<u8> {
    assert!(
        text.len().is_multiple_of(2),
        "hex must be whole bytes: {text}"
    );
    (0..text.len())
        .step_by(2)
        .map(|index| u8::from_str_radix(&text[index..index + 2], 16).expect("hex"))
        .collect()
}

fn to_hex(bytes: &[u8]) -> String {
    bytes.iter().map(|byte| format!("{byte:02x}")).collect()
}

#[test]
fn every_accepted_vector_decodes_to_a_wake_of_the_form_it_names() {
    for vector in vectors(&document()) {
        if !vector.accepted {
            continue;
        }
        let decoded = Frame::decode(&vector.bytes).unwrap_or_else(|error| {
            panic!(
                "{}: the relay could not read bytes computed from the CDDL: {error}. {}",
                vector.name, vector.reason
            )
        });
        let Frame::Wake(body) = &decoded else {
            panic!(
                "{}: decoded to {decoded:?}, which is not a WAKE",
                vector.name
            );
        };
        assert_eq!(decoded.tag(), FrameTag::Wake);
        assert_eq!(
            body.form(),
            vector.form,
            "{}: the file says form {} and the relay read form {}",
            vector.name,
            vector.form,
            body.form()
        );
    }
}

#[test]
fn every_accepted_vector_is_reproduced_byte_for_byte() {
    // The direction that catches an encoder which is wrong in the same way as its own
    // decoder. Re-encoding what was decoded is not a round trip against this build's
    // own opinion: the bytes came from the CDDL.
    for vector in vectors(&document()) {
        if !vector.accepted {
            continue;
        }
        let decoded = Frame::decode(&vector.bytes).expect("an accepted vector decodes");
        assert_eq!(
            to_hex(&decoded.encode()),
            to_hex(&vector.bytes),
            "{}: the relay re-encodes this frame differently. {}",
            vector.name,
            vector.reason
        );
    }
}

#[test]
fn every_rejected_vector_is_refused_with_the_class_the_file_names() {
    // Every refusal in this corpus is `reject`, which is the class that means
    // permanently wrong as sent. A relay answering `denied` or `retry` to any of them
    // would be telling a client to come back with bytes that will never be accepted.
    let now = 1_800_000_000_000u64;
    for vector in vectors(&document()) {
        if vector.accepted {
            continue;
        }
        let code = match Frame::decode(&vector.bytes) {
            Err(error) => error.code(),
            // The codec has no clock, so an expiry already past decodes and is refused
            // by the session against the relay's own observed time. Driven here rather
            // than asserted away, because the file says this frame is refused and it
            // has to be refused somewhere.
            Ok(frame) => refusal_from_the_session(frame, now).unwrap_or_else(|| {
                panic!(
                    "{}: the file says this is refused and nothing refused it. {}",
                    vector.name, vector.reason
                )
            }),
        };
        assert_eq!(
            code.class(),
            ErrorClass::Reject,
            "{}: refused with {}, and every refusal in this corpus is permanently wrong as sent",
            vector.name,
            code.qualified()
        );
        if let Some(named) = &vector.code {
            assert_eq!(
                &code.qualified(),
                named,
                "{}: the file names {named} and the relay answered {}. {}",
                vector.name,
                code.qualified(),
                vector.reason
            );
        }
    }
}

/// Drive one decoded frame through a `Ready` session and return the code it was
/// refused with, if it was refused.
///
/// The session is built the way `tests/session.rs` builds one, by driving the
/// machine rather than by reaching into it, so the refusal under test is the one a
/// real connection would get.
fn refusal_from_the_session(frame: Frame, now_ms: u64) -> Option<ErrorCode> {
    let config = Config::resolve(&Values::from_pairs([
        (keys::HOSTNAME, "relay.example".to_string()),
        (
            keys::DATABASE_URL,
            "postgres://weald:weald@127.0.0.1:5432/weald".to_string(),
        ),
        (
            keys::STORAGE_URL,
            "file:///tmp/weald-push-vectors".to_string(),
        ),
    ]))
    .expect("the configuration resolves");
    let mut session = Session::new(&config);
    session.handle(
        Frame::Connect {
            version: PROTOCOL_VERSION,
            groups: Vec::new(),
            sent_at: now_ms,
        },
        now_ms,
    );
    session.authenticated(0);
    let frames = match session.handle(frame, now_ms) {
        Reaction::Reply(frames) | Reaction::ReplyAndClose(frames) => frames,
        // Accepted for work, which is not a refusal.
        Reaction::Defer(_) => return None,
    };
    frames.iter().find_map(|frame| match frame {
        Frame::Error(error) => Some(error.code),
        _ => None,
    })
}

#[test]
fn the_corpus_covers_all_six_forms_and_every_push_code() {
    // Coverage of the closed sets, checked against the sets rather than against a
    // number. A form or a code with no vector is a decision no cross-implementation
    // test has ever exercised.
    let vectors = vectors(&document());
    for form in 1u8..=6 {
        assert!(
            vectors
                .iter()
                .any(|vector| vector.form == form && vector.accepted),
            "no accepted vector carries form {form}"
        );
    }
    let named: Vec<&String> = vectors
        .iter()
        .filter_map(|vector| vector.code.as_ref())
        .collect();
    assert!(
        named
            .iter()
            .any(|code| *code == &ErrorCode::PushHandleMalformed.qualified()),
        "the corpus names no `reject/push_handle_malformed` case, which is the one code the \
         WAKE frame added to the codec"
    );
    // And the refusals are a real fraction of the corpus: a file of nothing but happy
    // paths would pass every codec anybody wrote.
    let refusals = vectors.iter().filter(|vector| !vector.accepted).count();
    assert!(
        refusals >= 6,
        "only {refusals} refusals in the corpus, which is not enough to have tested a decoder"
    );
}

#[test]
fn the_file_and_the_build_agree_on_every_number_the_frame_depends_on() {
    // The constants the vectors are meaningless without. A client that thought the
    // handle was 32 bytes would send registrations this relay refuses, and the refusal
    // would look like a bug rather than like a disagreement.
    let document = document();
    assert_eq!(
        document["protocol_version"].as_u64(),
        Some(u64::from(PROTOCOL_VERSION))
    );
    assert_eq!(
        document["max_wake_frame_bytes"].as_u64(),
        Some(wealdrelay::frame::MAX_WAKE_BYTES as u64)
    );
    assert_eq!(
        document["max_register_url_bytes"].as_u64(),
        Some(wealdrelay::push::MAX_REGISTER_URL_BYTES as u64)
    );
    assert_eq!(
        document["handle_bytes"].as_u64(),
        Some(wealdrelay::push::HANDLE_BYTES as u64)
    );
    // The category bits, by name, because the ringer branches on the name and the
    // relay masks on the bit.
    let categories = &document["categories"];
    for category in wealdrelay::push::Category::ALL {
        assert_eq!(
            categories[category.as_str()].as_u64(),
            Some(u64::from(category.bit())),
            "the file and the build disagree about the {} bit",
            category.as_str()
        );
    }
}

#[test]
fn the_relay_encodes_the_bodies_the_file_describes() {
    // The last direction: build the body from the file's own `fields`, encode it here,
    // and compare against the file's bytes. Nothing in this test is derived from the
    // bytes under test, which is what makes it an independent check rather than a
    // second round trip.
    let document = document();
    let mut checked = 0;
    for case in document["vectors"].as_array().expect("a vectors array") {
        let vector = Vector::read(0, case);
        if !vector.accepted {
            continue;
        }
        let fields = &case["fields"];
        let body = match vector.form {
            1 => WakeBody::Register {
                handle: hex_to_bytes(fields["handle"].as_str().expect("handle")),
                categories: u8::try_from(fields["categories"].as_u64().expect("categories"))
                    .expect("a byte"),
                expires_at: fields["expires_at"].as_u64().expect("expires_at"),
            },
            2 => WakeBody::Registered {
                expires_at: fields["expires_at"].as_u64().expect("expires_at"),
            },
            3 => WakeBody::Clear,
            4 => WakeBody::Cleared,
            5 => WakeBody::Query,
            6 => WakeBody::Capability {
                enabled: fields["enabled"].as_bool().expect("enabled"),
                register_url: fields["register_url"]
                    .as_str()
                    .expect("register_url")
                    .to_string(),
            },
            other => panic!("{}: form {other} is not one of the six", vector.name),
        };
        assert_eq!(
            to_hex(&Frame::Wake(body).encode()),
            to_hex(&vector.bytes),
            "{}: the relay encodes the fields this file describes as different bytes. {}",
            vector.name,
            vector.reason
        );
        checked += 1;
    }
    assert!(checked >= 6, "only {checked} accepted vectors were rebuilt");
}
