// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Dicyanin Labs
//! The relay checked against the client, on the one function they must agree
//! about.
//!
//! `specs/backend/relay/wire.md`: `hash` is what the relay recomputes on accept
//! and what deduplicates a retry. That is only a real check if both
//! implementations mean the same function by it. Two encoders that differ by one
//! byte give one message two addresses, and then a retry after a dropped
//! connection stores a second copy instead of being answered with the existing
//! `seq`.
//!
//! So the vectors in `specs/backend/contracts/wire/vectors/content-address.json`
//! are generated by the **client's** code, by `scripts/fixture-log.sh --vectors`,
//! which compiles `Sources/Sync`. This suite asserts the relay reproduces them. A
//! Rust test asserting against a Rust-generated value would prove nothing at all.
//!
//! `scripts/backend-gate.sh 4` regenerates the file from Swift and fails on any
//! difference, so a change to either encoder is caught by the side that did not
//! change it.

use std::path::PathBuf;

use wealdrelay::cbor;
use wealdrelay::envelope::{content_hash, Encryption, Envelope, VERSION};

fn vectors_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../specs/backend/contracts/wire/vectors/content-address.json")
}

fn hex_to_bytes(text: &str) -> Vec<u8> {
    (0..text.len())
        .step_by(2)
        .map(|index| u8::from_str_radix(&text[index..index + 2], 16).expect("hex"))
        .collect()
}

fn to_hex(bytes: &[u8]) -> String {
    bytes.iter().map(|byte| format!("{byte:02x}")).collect()
}

#[test]
fn the_relay_reproduces_every_content_address_the_client_computed() {
    let text = std::fs::read_to_string(vectors_path()).expect(
        "the vector file must be checked in; regenerate with scripts/fixture-log.sh --vectors",
    );
    let document: serde_json::Value = serde_json::from_str(&text).expect("valid json");
    let cases = document["cases"].as_array().expect("a cases array");
    assert!(
        cases.len() >= 10,
        "the vector set has shrunk, which is how a boundary case gets quietly dropped"
    );

    for case in cases {
        let name = case["name"].as_str().unwrap_or("unnamed");
        let v = u8::try_from(case["v"].as_u64().expect("v")).expect("v fits");
        assert_eq!(
            v, VERSION,
            "{name}: the vector is for another protocol version"
        );
        let enc = Encryption::from_u8(
            u8::try_from(case["enc"].as_u64().expect("enc")).expect("enc fits"),
        )
        .expect("a known enc");
        let group = hex_to_bytes(case["group"].as_str().expect("group"));
        let epoch = case["epoch"].as_u64().expect("epoch");
        // The ciphertext is described rather than inlined, because one case is a
        // megabyte and a checked-in megabyte of hex would be a file nobody reads.
        let ct_len = usize::try_from(case["ct_len"].as_u64().expect("ct_len")).expect("len fits");
        let ct = match case["ct_byte"].as_u64() {
            None => Vec::new(),
            Some(byte) => vec![u8::try_from(byte).expect("byte fits"); ct_len],
        };
        assert_eq!(
            ct.len(),
            ct_len,
            "{name}: the ciphertext description is wrong"
        );

        let computed = content_hash(v, enc, &group, epoch, &ct);
        assert_eq!(
            to_hex(&computed),
            case["hash"].as_str().expect("hash"),
            "{name}: the relay and the client disagree about the content address"
        );

        // And the whole encoded envelope, so the relay's encoder is checked against
        // the client's rather than only its hasher. The envelope is built the way
        // the client builds one: `seq` and `ts` are zero until a relay assigns them.
        let envelope = Envelope {
            v,
            enc,
            group,
            epoch,
            seq: 0,
            ts: 0,
            hash: computed,
            ct,
        };
        let encoded = envelope.encode();
        assert_eq!(
            to_hex(blake3::hash(&encoded).as_bytes()),
            case["encoded_sha"].as_str().expect("encoded_sha"),
            "{name}: the relay and the client encode the envelope differently"
        );

        // Round trip, so a decoder that accepted the bytes but reconstructed a
        // different envelope would be caught here rather than at a client.
        assert_eq!(
            Envelope::decode(&encoded).expect("decodes"),
            envelope,
            "{name}"
        );
    }
}

#[test]
fn the_canonical_encoding_of_a_header_field_is_the_one_the_client_writes() {
    // The pieces the address is computed over, checked individually, so a failure
    // above says which field moved rather than only that something did. These are
    // the same byte sequences `Tests/DeterministicCBORTests.swift` asserts.
    assert_eq!(cbor::uint(1), vec![0x01]);
    assert_eq!(cbor::uint(0), vec![0x00]);
    assert_eq!(cbor::uint(23), vec![0x17]);
    assert_eq!(cbor::uint(24), vec![0x18, 0x18]);
    assert_eq!(
        cbor::uint(4_294_967_296),
        vec![0x1b, 0, 0, 0, 1, 0, 0, 0, 0]
    );
    assert_eq!(cbor::bytes(&[]), vec![0x40]);
    assert_eq!(cbor::bytes(&[1, 2, 3]), vec![0x43, 1, 2, 3]);
    // A 32-byte group id crosses into the one-byte length argument, which is the
    // boundary a hand-rolled encoder gets wrong.
    assert_eq!(cbor::bytes(&[0u8; 32])[..2], [0x58, 0x20]);
}
