// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Dicyanin Labs
//! The access set against Postgres: read the current state, apply one transition,
//! and answer the one question `AUTH` asks.
//!
//! Every rule lives in the parent module and none of them live here. What is here
//! is the transaction boundary, because the transition has to be atomic against a
//! concurrent publication: `wire.md` requires the relay to check "version is exactly
//! the previous version plus one" and to insert in one database transaction, and a
//! check-then-insert would let two authorizers both believe they had won.
//!
//! ## Why the chain is kept
//!
//! `relay_access_set` is append-only. The implicit-void rule for provisional grants
//! needs history: a grant is void once an accepted set has contained the joiner's
//! hash and a later accepted set does not. A relay holding only the current set
//! could not tell a set that never caught up with a new joiner, which must not void
//! the grant, from one that deliberately dropped a principal it previously carried,
//! which must.

use sqlx::{PgPool, Postgres, Row, Transaction};

use super::{entry_hash, AccessError, AccessSet, Prior, Probation, RecoveryQuorum, SignedAs};

/// How long a recovery principal must wait between rotations.
pub const ROTATION_WINDOW_HOURS: i64 = 24;

/// Why a database call could not answer.
///
/// Separate from ``AccessError``: one is a client that published something wrong,
/// the other is a relay that could not look. They are answered with different
/// classes and conflating them would tell a correct client to stop retrying.
#[derive(Debug, thiserror::Error)]
pub enum StoreError {
    #[error("access store: {0}")]
    Database(String),
    #[error("{0}")]
    Refused(#[from] AccessError),
}

fn db(error: sqlx::Error) -> StoreError {
    StoreError::Database(error.to_string())
}

/// What a workspace's access state looks like right now.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Current {
    pub salt: Vec<u8>,
    pub prior: Option<Prior>,
    pub probations: Vec<Probation>,
}

/// The salt for a workspace, generating one on first use.
///
/// Generated by the relay and never rotated: rotating it would invalidate every
/// entry hash in the chain at once. `on conflict do nothing` plus a re-read rather
/// than a check-then-insert, because two connections publishing a genesis set at the
/// same moment must agree about the salt or their entry hashes disagree forever.
pub async fn salt(pool: &PgPool, workspace: &str) -> Result<Vec<u8>, StoreError> {
    let fresh: [u8; 32] = random_salt();
    sqlx::query(
        "insert into relay_workspace (workspace_id, salt) values ($1, $2) \
         on conflict (workspace_id) do nothing",
    )
    .bind(workspace)
    .bind(fresh.as_slice())
    .execute(pool)
    .await
    .map_err(db)?;
    let row = sqlx::query("select salt from relay_workspace where workspace_id = $1")
        .bind(workspace)
        .fetch_one(pool)
        .await
        .map_err(db)?;
    row.try_get::<Vec<u8>, _>("salt").map_err(db)
}

/// Thirty-two bytes nobody can predict.
///
/// Straight from the operating system. Deliberately not a hash of the workspace id
/// and a clock: a salt an attacker can derive is a salt that links a stolen access
/// set against key material seen in another workspace, in a backup, or in a leak,
/// which is the one thing the salt exists to prevent.
///
/// A failure here is fatal rather than fallible. There is no weaker salt worth
/// falling back to, and a relay whose kernel will not give it randomness has a
/// problem no branch in this file can improve.
fn random_salt() -> [u8; 32] {
    let mut bytes = [0u8; 32];
    getrandom::fill(&mut bytes).expect("the operating system must provide randomness");
    bytes
}

/// Read everything a transition is judged against.
pub async fn current(pool: &PgPool, workspace: &str) -> Result<Current, StoreError> {
    let salt = salt(pool, workspace).await?;
    let prior = read_prior(pool, workspace).await?;
    let probations = read_probations(pool, workspace).await?;
    Ok(Current {
        salt,
        prior,
        probations,
    })
}

async fn read_prior(pool: &PgPool, workspace: &str) -> Result<Option<Prior>, StoreError> {
    let Some(row) = sqlx::query(
        "select version, digest from relay_access_set where workspace_id = $1 \
         order by version desc limit 1",
    )
    .bind(workspace)
    .fetch_optional(pool)
    .await
    .map_err(db)?
    else {
        return Ok(None);
    };
    let version: i64 = row.try_get("version").map_err(db)?;
    let digest: Vec<u8> = row.try_get("digest").map_err(db)?;
    let entries = sqlx::query(
        "select entry_hash from relay_access_entry where workspace_id = $1 and version = $2 \
         order by entry_hash",
    )
    .bind(workspace)
    .bind(version)
    .fetch_all(pool)
    .await
    .map_err(db)?
    .into_iter()
    .map(|row| row.try_get::<Vec<u8>, _>("entry_hash").map_err(db))
    .collect::<Result<Vec<_>, _>>()?;

    let principals = sqlx::query(
        "select role, pubkey from relay_access_principal where workspace_id = $1 and version = $2 \
         order by pubkey",
    )
    .bind(workspace)
    .bind(version)
    .fetch_all(pool)
    .await
    .map_err(db)?;
    let mut authorizers = Vec::new();
    let mut recovery = Vec::new();
    let mut quorum_keys = Vec::new();
    for row in principals {
        let role: String = row.try_get("role").map_err(db)?;
        let pubkey: Vec<u8> = row.try_get("pubkey").map_err(db)?;
        match role.as_str() {
            "authorizer" => authorizers.push(pubkey),
            "recovery" => recovery.push(pubkey),
            // The closed set is a check constraint on the column, so anything else
            // cannot be in the table. Named rather than defaulted so a fourth role
            // is a compile error here.
            _ => quorum_keys.push(pubkey),
        }
    }
    let quorum = match sqlx::query(
        "select threshold from relay_access_quorum where workspace_id = $1 and version = $2",
    )
    .bind(workspace)
    .bind(version)
    .fetch_optional(pool)
    .await
    .map_err(db)?
    {
        Some(row) => {
            let threshold: i16 = row.try_get("threshold").map_err(db)?;
            Some(RecoveryQuorum {
                // In range by `relay_access_quorum_threshold_in_byte_range`. The
                // constraint is the guard rather than a fallback here, because a
                // fallback would be a branch no row can reach.
                threshold: threshold as u8,
                keys: quorum_keys,
                sigs: Vec::new(),
            })
        }
        None => None,
    };

    Ok(Some(Prior {
        // Not negative by `relay_access_set_version_not_negative`.
        version: version as u64,
        digest,
        entries,
        authorizers,
        recovery,
        quorum,
    }))
}

async fn read_probations(pool: &PgPool, workspace: &str) -> Result<Vec<Probation>, StoreError> {
    let rows = sqlx::query(
        "select device, introduced_at, pending from relay_access_probation \
         where workspace_id = $1 and cleared_at is null order by device",
    )
    .bind(workspace)
    .fetch_all(pool)
    .await
    .map_err(db)?;
    let mut out = Vec::with_capacity(rows.len());
    for row in rows {
        let introduced: i64 = row.try_get("introduced_at").map_err(db)?;
        out.push(Probation {
            device: row.try_get("device").map_err(db)?,
            // Not negative by `relay_access_probation_version_not_negative`.
            introduced_at: introduced as u64,
            pending: row.try_get::<Vec<Vec<u8>>, _>("pending").map_err(db)?,
        });
    }
    Ok(out)
}

/// Has this recovery principal rotated inside the window?
pub async fn rotated_recently(
    pool: &PgPool,
    workspace: &str,
    recovery_key: &[u8],
) -> Result<bool, StoreError> {
    let row = sqlx::query(
        "select count(*) as recent from relay_recovery_rotation \
         where workspace_id = $1 and recovery_key = $2 \
           and attempted_at > now() - make_interval(hours => $3)",
    )
    .bind(workspace)
    .bind(recovery_key)
    .bind(ROTATION_WINDOW_HOURS as i32)
    .fetch_one(pool)
    .await
    .map_err(db)?;
    let recent: i64 = row.try_get("recent").map_err(db)?;
    Ok(recent > 0)
}

/// What accepting a publication changed, for the caller that has to act on it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Accepted {
    pub version: u64,
    pub digest: Vec<u8>,
    pub signed_as: SignedAs,
    /// Entry hashes the prior set carried and this one does not. Their sockets
    /// close, which is the half of offboarding the relay owns.
    pub disconnect: Vec<Vec<u8>>,
    pub opened_probation: Option<Vec<u8>>,
    pub cleared_probation: Vec<Vec<u8>>,
}

/// Judge a publication and, if it holds, apply it in one transaction.
pub async fn publish(
    pool: &PgPool,
    workspace: &str,
    candidate: &AccessSet,
    body: &[u8],
) -> Result<Accepted, StoreError> {
    let state = current(pool, workspace).await?;
    let recently = match state.prior.as_ref() {
        Some(prior) if prior.recovery.contains(&candidate.signer) => {
            rotated_recently(pool, workspace, &candidate.signer).await?
        }
        // Nothing to rate limit: a signer that is not a prior recovery principal
        // cannot take the rotation at all, and `judge` refuses it on that ground.
        _ => false,
    };
    let (signed_as, effects) = super::judge(
        candidate,
        state.prior.as_ref(),
        &state.salt,
        &state.probations,
        recently,
    )?;

    let digest = candidate.digest().to_vec();
    let mut transaction = pool.begin().await.map_err(db)?;

    // The compare-and-swap. `insert` with the primary key on (workspace, version)
    // is the swap: a concurrent publication of the same version loses here rather
    // than in a check that ran a moment earlier.
    let inserted = sqlx::query(
        "insert into relay_access_set \
         (workspace_id, version, digest, prev_hash, issued_at, signer, signed_as, body) \
         values ($1, $2, $3, $4, $5, $6, $7, $8) on conflict do nothing",
    )
    .bind(workspace)
    .bind(candidate.version as i64)
    .bind(&digest)
    .bind(&candidate.prev_hash)
    .bind(candidate.issued_at as i64)
    .bind(&candidate.signer)
    .bind(signed_as.label())
    .bind(body)
    .execute(&mut *transaction)
    .await
    .map_err(db)?;
    if inserted.rows_affected() == 0 {
        // Somebody else published this version between the read and the insert.
        // The client replays its roster operation against the current state rather
        // than silently overwriting a concurrent change.
        return Err(StoreError::Refused(AccessError::VersionNotNext {
            expected: candidate.version,
            got: candidate.version,
        }));
    }

    for entry in &candidate.entries {
        sqlx::query(
            "insert into relay_access_entry (workspace_id, version, entry_hash) \
             values ($1, $2, $3)",
        )
        .bind(workspace)
        .bind(candidate.version as i64)
        .bind(entry)
        .execute(&mut *transaction)
        .await
        .map_err(db)?;
    }
    for (role, keys) in [
        ("authorizer", &candidate.authorizers),
        ("recovery", &candidate.recovery),
    ] {
        for key in keys {
            insert_principal(&mut transaction, workspace, candidate.version, role, key).await?;
        }
    }
    if let Some(quorum) = &candidate.quorum {
        for key in &quorum.keys {
            insert_principal(
                &mut transaction,
                workspace,
                candidate.version,
                "quorum",
                key,
            )
            .await?;
        }
        sqlx::query(
            "insert into relay_access_quorum (workspace_id, version, threshold) values ($1, $2, $3)",
        )
        .bind(workspace)
        .bind(candidate.version as i64)
        .bind(i16::from(quorum.threshold))
        .execute(&mut *transaction)
        .await
        .map_err(db)?;
    }

    if matches!(signed_as, SignedAs::Recovery) {
        sqlx::query(
            "insert into relay_recovery_rotation (workspace_id, recovery_key) values ($1, $2)",
        )
        .bind(workspace)
        .bind(&candidate.signer)
        .execute(&mut *transaction)
        .await
        .map_err(db)?;
    }

    let mut opened = None;
    if let Some(probation) = &effects.opens_probation {
        sqlx::query(
            "insert into relay_access_probation (workspace_id, device, introduced_at, pending) \
             values ($1, $2, $3, $4) \
             on conflict (workspace_id, device) do update \
             set introduced_at = excluded.introduced_at, pending = excluded.pending, \
                 cleared_at = null, cleared_version = null",
        )
        .bind(workspace)
        .bind(&probation.device)
        .bind(probation.introduced_at as i64)
        .bind(&probation.pending)
        .execute(&mut *transaction)
        .await
        .map_err(db)?;
        opened = Some(probation.device.clone());
    }
    for device in &effects.clears_probation {
        sqlx::query(
            "update relay_access_probation set cleared_at = now(), cleared_version = $3 \
             where workspace_id = $1 and device = $2 and cleared_at is null",
        )
        .bind(workspace)
        .bind(device)
        .bind(candidate.version as i64)
        .execute(&mut *transaction)
        .await
        .map_err(db)?;
    }

    // Provisional grants, both halves of the implicit rule. A grant whose hash this
    // set carries is marked as seen; a grant that was seen before and is not in this
    // set is void. That ordering is what tells "never caught up" from "deliberately
    // dropped".
    sqlx::query(
        "update relay_provisional_grant set seen_version = $3 \
         where workspace_id = $1 and voided_at is null and device_hash = any($2)",
    )
    .bind(workspace)
    .bind(&candidate.entries)
    .bind(candidate.version as i64)
    .execute(&mut *transaction)
    .await
    .map_err(db)?;
    sqlx::query(
        "update relay_provisional_grant set voided_at = now(), voided_reason = 'superseded' \
         where workspace_id = $1 and voided_at is null and seen_version is not null \
           and not (device_hash = any($2))",
    )
    .bind(workspace)
    .bind(&candidate.entries)
    .execute(&mut *transaction)
    .await
    .map_err(db)?;

    // Genesis, and the one moment the relay's own key dies.
    //
    // Inside this transaction rather than after it, because
    // `specs/backend/relay/invites.md` requires one: "In one transaction the relay
    // accepts that set, retires the reservation, marks the invite spent, and zeroes
    // the genesis private key." Two transactions would leave a window in which the
    // trust root exists and the key that could mint a rival one still does.
    // Answers false for every publication that is not the genesis one, which is all
    // but at most one publication in a workspace's life.
    crate::invite::genesis::consume_in_tx(&mut transaction, workspace, candidate, &state.salt)
        .await
        .map_err(db)?;

    transaction.commit().await.map_err(db)?;

    Ok(Accepted {
        version: candidate.version,
        digest,
        signed_as,
        disconnect: effects.removed,
        opened_probation: opened,
        cleared_probation: effects.clears_probation,
    })
}

async fn insert_principal(
    transaction: &mut Transaction<'_, Postgres>,
    workspace: &str,
    version: u64,
    role: &str,
    key: &[u8],
) -> Result<(), StoreError> {
    sqlx::query(
        "insert into relay_access_principal (workspace_id, version, role, pubkey) \
         values ($1, $2, $3, $4) on conflict do nothing",
    )
    .bind(workspace)
    .bind(version as i64)
    .bind(role)
    .bind(key)
    .execute(&mut **transaction)
    .await
    .map_err(db)?;
    Ok(())
}

/// The question `AUTH` asks, and the only one.
///
/// May this key open a socket to this workspace right now? Three ways to be yes and
/// they are checked in the order that costs least: the newest accepted set carries
/// the hash, or a live provisional grant does. There is no third.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Admission {
    /// Named in the newest accepted set.
    InSet,
    /// Connecting under a provisional grant that has not expired or been voided.
    Provisional,
    /// Not permitted. The socket is refused and no reason is given on the wire
    /// beyond the code: telling a stranger whether a workspace exists, or whether
    /// their key was once in it, is membership information.
    Refused,
}

pub async fn admits(
    pool: &PgPool,
    workspace: &str,
    device_key: &[u8],
) -> Result<Admission, StoreError> {
    let salt = salt(pool, workspace).await?;
    let hash = entry_hash(device_key, &salt);
    // `query_scalar` rather than a row plus a `try_get`. Both spellings answer the same
    // question; this one has one failure path instead of two, and the second of those
    // two was unreachable: the column is an alias in this query's own text so the
    // lookup cannot miss, a SQL `exists` is `bool` by the parser regardless of the
    // catalog, and `exists` is never null. A `?` no database state can reach is a line
    // no test can honestly cover, and the coverage floor for this file is 100 percent
    // with no exclusions permitted anywhere near the access set
    // (`specs/backend/build/testing.md`). The fix is to not write the branch.
    let present: bool = sqlx::query_scalar(
        "select exists ( \
             select 1 from relay_access_entry e \
             where e.workspace_id = $1 and e.entry_hash = $2 \
               and e.version = (select max(version) from relay_access_set \
                                where workspace_id = $1) \
         )",
    )
    .bind(workspace)
    .bind(&hash)
    .fetch_one(pool)
    .await
    .map_err(db)?;
    if present {
        return Ok(Admission::InSet);
    }

    let live: bool = sqlx::query_scalar(
        "select exists ( \
             select 1 from relay_provisional_grant \
             where workspace_id = $1 and device_hash = $2 \
               and voided_at is null and expires_at > now() \
         )",
    )
    .bind(workspace)
    .bind(&hash)
    .fetch_one(pool)
    .await
    .map_err(db)?;
    if live {
        return Ok(Admission::Provisional);
    }
    Ok(Admission::Refused)
}

/// Resolve the workspace from a connection's groups and publish into it.
///
/// One function for the same reason `admission` is one: the workspace lookup and the
/// publication are two queries with one failure meaning, and two `Database` arms in
/// the caller would be two ways to answer "come back". The workspace is this relay's
/// own answer for one of the groups the connection named, never the one carried in
/// the set: a publication naming somebody else's workspace must not be applied to it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Published {
    /// The connection named no group this relay knows.
    UnknownGroup,
    Accepted(Accepted),
}

pub async fn publish_for(
    pool: &PgPool,
    groups: &[Vec<u8>],
    candidate: &AccessSet,
    body: &[u8],
) -> Result<Published, StoreError> {
    for group in groups {
        if let Some(workspace) = workspace_of(pool, group).await? {
            return publish(pool, &workspace, candidate, body)
                .await
                .map(Published::Accepted);
        }
    }

    // Nothing the connection named is a group this relay knows, which is the
    // ordinary state of a workspace that has never had one: groups are created by
    // the trust root, and the trust root is admitted by this very publication.
    //
    // So the second way in, and only for that case: a device holding the live,
    // unconsumed reservation on a workspace's bootstrap invite is founding that
    // workspace, and the relay can say which one. One device per workspace, only
    // until the seat is spent, and only for a set whose sole authorizer is that
    // device, which `genesis::consume` checks again before it destroys the key.
    if candidate.authorizers.len() == 1 {
        if let Some(workspace) =
            crate::invite::genesis::founding_workspace(pool, &candidate.authorizers[0])
                .await
                .map_err(|error| StoreError::Database(error.to_string()))?
        {
            return publish(pool, &workspace, candidate, body)
                .await
                .map(Published::Accepted);
        }
    }
    Ok(Published::UnknownGroup)
}

/// Everything `AUTH` needs to know, in one read.
///
/// One function rather than four calls from `ws::admit`, because each call was a
/// separate "the relay could not look" arm and four arms for one answer is four
/// chances to answer a different way. The caller has one failure path and it means
/// exactly one thing: come back.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Verdict {
    /// The connection named no group this relay knows, so it named no workspace.
    UnknownGroup,
    /// The workspace has no accepted set at all. The pre-genesis state.
    Bootstrap(String),
    /// Admitted, with the salted hash this connection is known by. Carried out so
    /// the hub can be told who the socket belongs to without a second round trip,
    /// which is what makes eviction on revocation possible at all.
    Admitted { entry: Vec<u8>, workspace: String },
    /// Not permitted.
    Refused,
}

pub async fn admission(
    pool: &PgPool,
    groups: &[Vec<u8>],
    device_key: &[u8],
) -> Result<Verdict, StoreError> {
    let mut workspace = None;
    for group in groups {
        if let Some(found) = workspace_of(pool, group).await? {
            workspace = Some(found);
            break;
        }
    }
    // The same second way in that `publish_for` has, and for the same moment: a
    // workspace whose trust root has not been admitted yet has no groups, because
    // groups are made by the trust root. A device holding the live, unconsumed
    // reservation on that workspace's bootstrap invite is the one device that can
    // be answered here, and what it is answered is `Bootstrap`, which permits
    // exactly one frame.
    let workspace = match workspace {
        Some(workspace) => workspace,
        None => match crate::invite::genesis::founding_workspace(pool, device_key)
            .await
            .map_err(|error| StoreError::Database(error.to_string()))?
        {
            Some(workspace) => workspace,
            None => return Ok(Verdict::UnknownGroup),
        },
    };
    let salt = salt(pool, &workspace).await?;
    let hash = entry_hash(device_key, &salt);
    match admits(pool, &workspace, device_key).await? {
        Admission::InSet | Admission::Provisional => Ok(Verdict::Admitted {
            entry: hash,
            workspace,
        }),
        // No set at all is a different answer from "your key is not in the set", and
        // this is the only place the difference is actionable.
        Admission::Refused => match read_prior(pool, &workspace).await? {
            Some(_) => Ok(Verdict::Refused),
            None => Ok(Verdict::Bootstrap(workspace)),
        },
    }
}

/// Record a provisional grant for a joiner.
///
/// Bounded at birth: one device hash, the invite's expiry, never renewable. A grant
/// for a hash that once held one starts over, `seen_version` included: the implicit
/// rule voids a grant whose principal an accepted set carried and a later one did
/// not, and carrying that mark into a freshly issued grant would void the new one on
/// the next publication for something the old one did.
///
/// The
/// invite machinery that creates these arrives with `specs/backend/relay/invites.md`;
/// what step 6 owes is that a grant, once it exists, dies exactly when the three
/// rules say it does.
pub async fn grant(
    pool: &PgPool,
    workspace: &str,
    device_hash: &[u8],
    expires_at_ms: i64,
) -> Result<(), StoreError> {
    sqlx::query(
        "insert into relay_provisional_grant (workspace_id, device_hash, expires_at) \
         values ($1, $2, to_timestamp($3::double precision / 1000)) \
         on conflict (workspace_id, device_hash) do update \
         set expires_at = excluded.expires_at, voided_at = null, voided_reason = null, \
             seen_version = null",
    )
    .bind(workspace)
    .bind(device_hash)
    .bind(expires_at_ms)
    .execute(pool)
    .await
    .map_err(db)?;
    Ok(())
}

/// Void every grant derived from a revoked invite, explicitly.
pub async fn revoke_grant(
    pool: &PgPool,
    workspace: &str,
    device_hash: &[u8],
) -> Result<bool, StoreError> {
    let done = sqlx::query(
        "update relay_provisional_grant set voided_at = now(), voided_reason = 'revoked' \
         where workspace_id = $1 and device_hash = $2 and voided_at is null",
    )
    .bind(workspace)
    .bind(device_hash)
    .execute(pool)
    .await
    .map_err(db)?;
    Ok(done.rows_affected() > 0)
}

/// What a client needs before it can build a publication.
///
/// The salt, and the head of the chain if there is one. Answered to any connection
/// that has authenticated or is bootstrapping, because a client cannot compute one
/// entry hash without the salt and therefore cannot publish any set at all: the
/// genesis publication `wire.md` requires of the trust root was unbuildable by any
/// real client until this existed. It tells the asker nothing it is not entitled to.
/// The salt is not a secret from the relay's peers (`wire.md`, "The relay holds the
/// workspace salt"), it hides nothing about who is in the set, and the version and
/// digest are already echoed to a publisher on every accepted rotation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct State {
    pub salt: Vec<u8>,
    /// The accepted head, or `None` before genesis.
    pub head: Option<(u64, Vec<u8>)>,
}

/// The state for the workspace one of these groups belongs to.
pub async fn state_for(pool: &PgPool, groups: &[Vec<u8>]) -> Result<Option<State>, StoreError> {
    for group in groups {
        if let Some(workspace) = workspace_of(pool, group).await? {
            return state_of(pool, &workspace).await.map(Some);
        }
    }
    Ok(None)
}

/// The same, for a workspace the caller has already resolved.
///
/// The genesis publisher needs this and cannot use the group form: it is asking for
/// the salt with which to compute the entries of the very first set, and the
/// workspace has no groups until that set admits somebody who can make one.
pub async fn state_of(pool: &PgPool, workspace: &str) -> Result<State, StoreError> {
    let salt = salt(pool, workspace).await?;
    let head = read_prior(pool, workspace)
        .await?
        .map(|prior| (prior.version, prior.digest));
    Ok(State { salt, head })
}

/// Which workspace a group belongs to.
///
/// The access check is per workspace and a connection names groups, so the two have
/// to be joined somewhere. Here, against the table the relay already keeps, rather
/// than by trusting a workspace id the client supplies in a frame.
pub async fn workspace_of(pool: &PgPool, group: &[u8]) -> Result<Option<String>, StoreError> {
    let row = sqlx::query("select workspace_id from relay_group where group_id = $1")
        .bind(group)
        .fetch_optional(pool)
        .await
        .map_err(db)?;
    match row {
        Some(row) => Ok(Some(row.try_get::<String, _>("workspace_id").map_err(db)?)),
        None => Ok(None),
    }
}

/// How many principals this relay has admitted, across every workspace on it.
///
/// A count, and nothing else. `specs/backend/cloud/api.md` is unusually specific
/// about the shape: `POST /instances/:id/bootstrap` is available only while the
/// instance reports zero admitted principals, and "the relay exposes that count
/// and nothing else about the roster". Reprovision then branches on the same
/// number and is explicitly forbidden from learning whether the admitted
/// principal is the paying account, because that would link billing identity to
/// workspace identity.
///
/// So this returns a number. Not identities, not entry hashes, not a per
/// workspace breakdown: each of those is a trust-boundary change and belongs in
/// `specs/backend/relay/overview.md` rather than in a convenience return type.
///
/// Counted over the newest version of each workspace's access set, because that
/// is what "currently admitted" means: a device revoked in version 4 is in
/// version 3's entry list forever, and summing every version would report a
/// roster that has never existed. Zero before any set is published, which is the
/// state a freshly provisioned relay is in and the one the bootstrap claim
/// requires.
pub async fn admitted_principals(pool: &PgPool) -> Result<i64, StoreError> {
    let row = sqlx::query(
        "select count(*) as admitted from relay_access_entry e \
         join (select workspace_id, max(version) as version \
               from relay_access_set group by workspace_id) latest \
           on latest.workspace_id = e.workspace_id and latest.version = e.version",
    )
    .fetch_one(pool)
    .await
    .map_err(db)?;
    row.try_get::<i64, _>("admitted").map_err(db)
}
