// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Dicyanin Labs
//! RFC 9420's interop test vectors, driven through this binding rather than through
//! OpenMLS's own suite.
//!
//! `specs/backend/relay/mls-binding.md` asks for exactly this and says why: "RFC 9420 test
//! vectors, run against our binding rather than only against OpenMLS's own suite, so a
//! mistake in our marshalling is caught." OpenMLS already runs these vectors against its
//! internal types. That proves OpenMLS implements the RFC. It proves nothing at all about
//! the layer this crate adds on top: the `tls_serialize` and `tls_deserialize` pairings in
//! `src/session.rs`, the choice of which body a given seam function will accept, the
//! `Malformed` versus `Protocol` distinction the C ABI reports, and the provider
//! `src/store.rs` assembles out of `RustCrypto` and SQLite. Every one of those is ours and
//! every one of them can be wrong while OpenMLS is right.
//!
//! So each vector here enters through a public function of the seam: `Device::key_package`,
//! `Device::join_welcome`, `Device::join_external`, `Session::add` (which is
//! `read_key_package`), `Session::process`, `Session::ratchet_tree`, and the provider
//! reached through `Device::provider`.
//!
//! What a failure here means, by test:
//!
//! - An acceptance failure (a conformant vector coming back `Malformed`) means our decoder
//!   rejects messages a conformant peer will really send. In the shipped product that is a
//!   device that cannot be invited, cannot join, or drops group traffic on the floor.
//! - A re-encoding failure means the bytes we put on the wire are not the bytes the RFC
//!   describes, so every other implementation refuses us. `Device::key_package` publishes
//!   to the relay and `Session::ratchet_tree` hands a tree to a joiner, and both are
//!   compared here against vectors generated by other implementations.
//! - A negative-control failure means the acceptance assertions have no teeth: a decoder
//!   that accepted everything would pass them.
//! - A crypto-basics failure means `store::Provider` is wired to something that is not
//!   RFC 9420's key schedule primitives, which would be a silent interoperability break
//!   with no error message anywhere.
//!
//! The corpus is vendored under `tests/vectors/` with its provenance in
//! `tests/vectors/README.md`, and the first test in this file re-derives the digests, so a
//! corpus that drifted from the commit it claims to come from fails before anything is
//! read from it. A vector corpus with no provenance is not a conformance proof.
//!
//! Every test counts what it ran and what it skipped and asserts both exactly. A
//! conformance suite that ran zero vectors and reported success is the failure mode this
//! design is against, so no test here can pass by finding nothing to do.

use openmls::prelude::tls_codec::{Deserialize as _, Serialize as _, Size as _, VLBytes};
use openmls::prelude::{Ciphersuite, MlsMessageBodyIn, MlsMessageIn, RatchetTreeIn};
use openmls_traits::crypto::OpenMlsCrypto as _;
use openmls_traits::types::{HashType, HpkeCiphertext, HpkeConfig};
use openmls_traits::OpenMlsProvider as _;
use serde::Deserialize;

use weald_mls::session::{Config, Device, Session, CIPHERSUITE};
use weald_mls::status::Status;

// MARK: The corpus and its provenance

/// The upstream commit the vendored files were taken from. Recorded in three places on
/// purpose: here, in `tests/vectors/README.md`, and in the digests below. A corpus that
/// was quietly refreshed to make a failure go away has to defeat all three.
const UPSTREAM_COMMIT: &str = "89134d5de0222bd99598ba5849003d2e85e63116";

/// Each vendored file with the SHA-256 it had at ``UPSTREAM_COMMIT``.
const CORPUS: [(&str, &str); 3] = [
    (
        "crypto-basics.json",
        "17cfcf89af9f51d0f2aa7af77f6f9ec99376a039214b6d42a6f11646b83e8c29",
    ),
    (
        "messages.json",
        "b194abe1561995223482dbad51c180146920dc2f637e74d01e07a388308791fb",
    ),
    (
        "welcome.json",
        "06be9d5c99817ef2545e4b15b8e73fd9b604685a8e55b59ca168eda98e236502",
    ),
];

/// Files in the upstream `test-vectors/` directory that this suite deliberately does not
/// vendor, each with the reason. Written down rather than left implicit, because a reader
/// checking whether the gate is honest needs to see what was left out and why.
///
/// - `key-schedule.json`: the vector fixes an `init_secret` and a per-epoch
///   `commit_secret` and asks for the derived epoch secrets. Injecting those means
///   constructing OpenMLS's `KeySchedule` directly, which is crate-internal and reachable
///   only through the `test-utils` feature. Our seam's only key-schedule surface is
///   `Session::export`, and that is bound to a live group at a real epoch, so there is no
///   point to inject at. The provider wiring the vector would have exercised is covered by
///   `crypto-basics.json` instead, which drives the same `RustCrypto` instance
///   `store::Provider` hands OpenMLS.
/// - `passive-client-welcome.json`, `passive-client-handling-commit.json`,
///   `passive-client-random.json`: each supplies a joiner's `init_priv`,
///   `encryption_priv` and `signature_priv` and expects a client to join with them.
///   `Device` mints its own signing key on first use and keeps it in its own encrypted
///   store (`session::load_or_create_signer`), and the seam has no key-import function at
///   all. That is a deliberate property of the design, not an oversight, so these vectors
///   cannot be expressed without widening the twelve-function seam for a test. The joining
///   path they would prove is proved instead by `tests/session.rs`, which joins a real
///   welcome produced by a real add.
/// - `secret-tree.json`, `message-protection.json`, `transcript-hashes.json`,
///   `treekem.json`, `tree-validation.json`, `tree-operations.json`, `tree-math.json`,
///   `psk_secret.json`, `deserialization.json`: all address OpenMLS internals (the secret
///   tree, the transcript hash chain, tree math, PSK derivation) that our seam never
///   touches as bytes and cannot reach as types. Re-testing them here would be re-testing
///   OpenMLS, which is exactly what the spec says these vectors are not for.
const NOT_VENDORED: [&str; 13] = [
    "key-schedule.json",
    "passive-client-welcome.json",
    "passive-client-handling-commit.json",
    "passive-client-random.json",
    "secret-tree.json",
    "message-protection.json",
    "transcript-hashes.json",
    "treekem.json",
    "tree-validation.json",
    "tree-operations.json",
    "tree-math.json",
    "psk_secret.json",
    "deserialization.json",
];

/// One vendored file's bytes.
fn corpus(name: &str) -> Vec<u8> {
    let path = format!("{}/tests/vectors/{name}", env!("CARGO_MANIFEST_DIR"));
    std::fs::read(&path).unwrap_or_else(|error| panic!("reading {path}: {error}"))
}

// MARK: The seam under test

/// A device on its own in-memory database, for the same reason `tests/session.rs` uses
/// one: it is the same storage provider and the same SQL, without measuring the disk.
fn device(identity: &str) -> Device {
    Device::open(&Config {
        database: ":memory:".to_string(),
        identity: identity.as_bytes().to_vec(),
    })
    .expect("a device")
}

/// A group this device owns, used as the receiving end for every vector fed to
/// ``Session::process``. The vectors come from other implementations' groups, so nothing
/// here can ever decrypt: the point is which side of the decoder the refusal comes from.
fn group() -> Session {
    device("vectors")
        .create_group(b"weald-vector-group")
        .expect("a group")
}

/// What every acceptance assertion in this file really asserts.
///
/// `Malformed` is the one status that means our decoder rejected the bytes. Every other
/// status means the bytes decoded and something further in decided against them, which for
/// a vector from a stranger's group is the only possible outcome: a key package minted in
/// 2023 is outside its lifetime, a welcome is addressed to a key package we do not hold,
/// and an application message names a group id that is not ours. So a conformant vector
/// must fail, and it must fail on the far side of the marshalling.
fn decoded(what: &str, result: Result<(), Status>) {
    if let Err(status) = result {
        assert_ne!(
            status,
            Status::Malformed,
            "{what}: our decoder refused a conformant RFC 9420 vector"
        );
    }
}

/// How each vector fed to a seam function came back, as a status or nothing.
fn status<T>(result: weald_mls::status::Result<T>) -> Result<(), Status> {
    result.map(|_| ()).map_err(|error| error.status())
}

// MARK: messages.json

/// One entry of `messages.json`. Every field is a hex-encoded serialisation of one MLS
/// structure. The six this binding actually consumes are named; the rest are read but not
/// driven, and the reason is on ``MESSAGES_NOT_CONSUMED``.
#[derive(Deserialize)]
struct MessagesVector {
    #[serde(with = "hex::serde")]
    mls_welcome: Vec<u8>,
    #[serde(with = "hex::serde")]
    mls_group_info: Vec<u8>,
    #[serde(with = "hex::serde")]
    mls_key_package: Vec<u8>,
    #[serde(with = "hex::serde")]
    ratchet_tree: Vec<u8>,
    #[serde(with = "hex::serde")]
    public_message_application: Vec<u8>,
    #[serde(with = "hex::serde")]
    public_message_proposal: Vec<u8>,
    #[serde(with = "hex::serde")]
    public_message_commit: Vec<u8>,
    #[serde(with = "hex::serde")]
    private_message: Vec<u8>,
}

/// The fields of a `messages.json` entry this suite does not drive, and why.
///
/// All nine are bare RFC structures rather than `MLSMessage` framings. `group_secrets` is
/// what a joiner recovers from inside the welcome's HPKE-sealed secrets, so our seam only
/// ever sees it encrypted. The seven proposals and the commit are `FramedContent` bodies:
/// they reach a client wrapped in a `PublicMessage` or a `PrivateMessage` and never on
/// their own, and the three framed forms that do carry them are driven below. Feeding a
/// bare `Add` to `Session::process` would prove only that our decoder rejects something no
/// peer sends.
const MESSAGES_NOT_CONSUMED: [&str; 9] = [
    "group_secrets",
    "add_proposal",
    "update_proposal",
    "remove_proposal",
    "pre_shared_key_proposal",
    "re_init_proposal",
    "external_init_proposal",
    "group_context_extensions_proposal",
    "commit",
];

/// The ciphersuite of a `messages.json` entry.
///
/// Read off the key package's own bytes rather than from a JSON field, because
/// `messages.json` has no `cipher_suite` field and OpenMLS's `KeyPackageIn` exposes no
/// accessor before validation. The offsets are fixed by RFC 9420: an `MLSMessage` is
/// `ProtocolVersion version` then `WireFormat wire_format`, four bytes, and a `KeyPackage`
/// opens with `ProtocolVersion version` then `CipherSuite cipher_suite`, so the suite is
/// the sixth and seventh bytes. Cross-checked against the welcome in the same entry, whose
/// `CipherSuite` is its own first field, so a wrong offset cannot go unnoticed.
fn messages_ciphersuite(vector: &MessagesVector) -> u16 {
    let from_key_package =
        u16::from_be_bytes([vector.mls_key_package[6], vector.mls_key_package[7]]);
    let from_welcome = u16::from_be_bytes([vector.mls_welcome[4], vector.mls_welcome[5]]);
    assert_eq!(
        from_key_package, from_welcome,
        "the two structures in one entry disagree about the ciphersuite, so the offsets are wrong"
    );
    from_key_package
}

/// Every `messages.json` entry, and the ones at this build's one ciphersuite.
fn messages() -> (usize, Vec<MessagesVector>) {
    let raw = corpus("messages.json");
    let all: Vec<MessagesVector> = serde_json::from_slice(&raw).expect("messages.json parses");
    let total = all.len();
    let ours = u16::from(CIPHERSUITE);
    let mine: Vec<MessagesVector> = all
        .into_iter()
        .filter(|vector| messages_ciphersuite(vector) == ours)
        .collect();
    (total, mine)
}

#[test]
fn the_vendored_corpus_is_the_one_this_suite_was_pinned_against() {
    // Hashed with the same provider `store.rs` assembles, so this test also happens to be
    // the smallest possible check that the provider computes SHA-256 at all.
    let device = device("digest");
    let crypto = device.provider().crypto();
    for (name, expected) in CORPUS {
        let digest = crypto
            .hash(HashType::Sha2_256, &corpus(name))
            .expect("sha-256");
        assert_eq!(
            hex::encode(digest),
            expected,
            "{name} is not the file taken from mlswg/mls-implementations@{UPSTREAM_COMMIT}"
        );
    }
    // Three vendored, thirteen named as deliberately absent. Asserted so that a file
    // added to `tests/vectors/` without a digest, or a skip reason deleted along with the
    // vector it explained, fails here.
    assert_eq!(CORPUS.len(), 3);
    assert_eq!(NOT_VENDORED.len(), 13);
    assert_eq!(UPSTREAM_COMMIT.len(), 40);
}

#[test]
fn every_messages_vector_our_binding_consumes_is_accepted_rather_than_refused_as_malformed() {
    let (total, mine) = messages();
    // The corpus carries three ciphersuites. Ours is one of them, and the other two are
    // skipped: `mls-binding.md` says "no custom ciphersuite" and a build that accepted a
    // key package under a suite it does not implement would be negotiating its way into a
    // combination nobody tested.
    assert_eq!(total, 300, "the vendored messages.json changed size");
    assert_eq!(
        mine.len(),
        100,
        "the ciphersuite filter found the wrong set"
    );
    let skipped_for_ciphersuite = total - mine.len();
    assert_eq!(skipped_for_ciphersuite, 200);

    let mut run = 0_usize;
    for vector in &mine {
        let mut session = group();

        // `Session::add`, which is `read_key_package`: the relay hands this device a
        // stranger's key package and this is the function that decodes it.
        decoded(
            "mls_key_package through Session::add",
            status(session.add(&vector.mls_key_package)),
        );
        // `Device::join_welcome`: the ordinary invite path's own deserialiser.
        decoded(
            "mls_welcome through Device::join_welcome",
            status(device("joiner").join_welcome(&vector.mls_welcome)),
        );
        // `Device::join_external`: the self-join path's own deserialiser.
        decoded(
            "mls_group_info through Device::join_external",
            status(device("joiner").join_external(&vector.mls_group_info)),
        );
        // `Session::process`: the one function that eats bytes straight off the network,
        // in all four framings a group really sends.
        for (what, bytes) in [
            (
                "public_message_application",
                &vector.public_message_application,
            ),
            ("public_message_proposal", &vector.public_message_proposal),
            ("public_message_commit", &vector.public_message_commit),
            ("private_message", &vector.private_message),
        ] {
            decoded(
                &format!("{what} through Session::process"),
                status(session.process(bytes)),
            );
        }
        run += 7;
    }

    // Seven consumed shapes per entry, and nine fields per entry this seam never sees as
    // bytes. Seventeen is every field `messages.json` defines, so nothing in the file is
    // silently unaccounted for.
    assert_eq!(run, 700, "the suite did not drive what it claims to drive");
    assert_eq!(7 + MESSAGES_NOT_CONSUMED.len() + 1, 17);
    // The ratchet tree is the seventeenth field. It is consumed by this suite, but through
    // re-encoding rather than through an acceptance path, because no seam function takes a
    // ratchet tree in. The test below is where it runs.
}

#[test]
fn every_messages_vector_our_binding_re_encodes_reproduces_the_vector_bytes() {
    let (_, mine) = messages();
    assert_eq!(mine.len(), 100);

    let mut round_trips = 0_usize;
    let mut length_only = 0_usize;
    for vector in &mine {
        // The `MLSMessage` header is `ProtocolVersion` then `WireFormat`, four bytes, and
        // the body follows. OpenMLS's body enum is only serialisable behind its
        // `test-utils` feature, which this crate refuses to turn on for the reason
        // `session.rs` gives about `tree_hash`, so the body is compared against the tail.
        const HEADER: usize = 4;

        // `Device::key_package` publishes exactly this shape to the relay. If our encoding
        // of a key package is off by a byte, nobody can ever invite this device.
        match MlsMessageIn::tls_deserialize_exact(&vector.mls_key_package)
            .expect("a key package")
            .extract()
        {
            MlsMessageBodyIn::KeyPackage(package) => {
                assert_eq!(
                    package.tls_serialize_detached().expect("re-encoded"),
                    vector.mls_key_package[HEADER..],
                    "a key package does not survive our decode and encode"
                );
                round_trips += 1;
            }
            other => panic!("mls_key_package is not a key package: {other:?}"),
        }

        // The welcome `Session::add` produces for a joiner.
        match MlsMessageIn::tls_deserialize_exact(&vector.mls_welcome)
            .expect("a welcome")
            .extract()
        {
            MlsMessageBodyIn::Welcome(welcome) => {
                assert_eq!(
                    welcome.tls_serialize_detached().expect("re-encoded"),
                    vector.mls_welcome[HEADER..],
                    "a welcome does not survive our decode and encode"
                );
                round_trips += 1;
            }
            other => panic!("mls_welcome is not a welcome: {other:?}"),
        }

        // The three public framings and the private one, which between them are every
        // shape `Session::process` and `Session::encrypt` deal in.
        for (what, bytes) in [
            (
                "public_message_application",
                &vector.public_message_application,
            ),
            ("public_message_proposal", &vector.public_message_proposal),
            ("public_message_commit", &vector.public_message_commit),
        ] {
            match MlsMessageIn::tls_deserialize_exact(bytes)
                .expect("a public message")
                .extract()
            {
                MlsMessageBodyIn::PublicMessage(message) => {
                    assert_eq!(
                        message.tls_serialize_detached().expect("re-encoded"),
                        bytes[HEADER..],
                        "{what} does not survive our decode and encode"
                    );
                    round_trips += 1;
                }
                other => panic!("{what} is not a public message: {other:?}"),
            }
        }
        match MlsMessageIn::tls_deserialize_exact(&vector.private_message)
            .expect("a private message")
            .extract()
        {
            MlsMessageBodyIn::PrivateMessage(message) => {
                assert_eq!(
                    message.tls_serialize_detached().expect("re-encoded"),
                    vector.private_message[HEADER..],
                    "a private message does not survive our decode and encode"
                );
                round_trips += 1;
            }
            other => panic!("private_message is not a private message: {other:?}"),
        }

        // `Session::ratchet_tree` hands exactly this encoding to a joiner that needs the
        // tree out of band, and it is the one place this crate serialises something that
        // is not an `MlsMessageOut`. So it is checked against a tree another
        // implementation produced, whole, with no header to skip.
        let tree = RatchetTreeIn::tls_deserialize_exact(&vector.ratchet_tree).expect("a tree");
        assert_eq!(
            tree.tls_serialize_detached().expect("re-encoded"),
            vector.ratchet_tree,
            "a ratchet tree does not survive our decode and encode"
        );
        round_trips += 1;

        // The group info is the one shape with no byte-for-byte check available:
        // `VerifiableGroupInfo` only derives `TlsSerialize` under OpenMLS's `test-utils`
        // feature, and a group info cannot be turned into a serialisable `GroupInfo`
        // without the signer's key, which a vector does not carry. What is still provable
        // is that our decoder accounted for every byte of it: `tls_deserialize_exact`
        // rejects a trailing byte, and the decoded value's own encoded length equals the
        // vector's, so nothing was silently dropped in the middle either.
        let info =
            MlsMessageIn::tls_deserialize_exact(&vector.mls_group_info).expect("a group info");
        assert_eq!(
            info.tls_serialized_len(),
            vector.mls_group_info.len(),
            "our decode of a group info does not account for all of its bytes"
        );
        length_only += 1;
    }

    assert_eq!(
        round_trips, 700,
        "the re-encoding suite ran the wrong count"
    );
    assert_eq!(length_only, 100);
}

#[test]
fn a_messages_vector_with_a_byte_added_or_taken_away_is_refused_as_malformed() {
    // The negative control. Without it, every acceptance assertion above would pass
    // against a decoder that accepted anything at all, and this suite would be proving
    // nothing. Damaged bytes must come back `Malformed`, which is the status the C ABI
    // reports for hostile input and the one the caller drops a message on.
    let (_, mine) = messages();
    let mut refusals = 0_usize;
    // Ten entries rather than a hundred: the property is about the decoder, not about the
    // corpus, and every entry would only repeat it.
    for vector in mine.iter().take(10) {
        let mut session = group();
        let joiner = device("joiner");

        for bytes in [&vector.private_message, &vector.public_message_commit] {
            let mut longer = bytes.clone();
            longer.push(0x00);
            assert_eq!(
                session.process(&longer).expect_err("refused").status(),
                Status::Malformed
            );
            let shorter = &bytes[..bytes.len() - 1];
            assert_eq!(
                session.process(shorter).expect_err("refused").status(),
                Status::Malformed
            );
            refusals += 2;
        }

        let mut longer = vector.mls_key_package.clone();
        longer.push(0x00);
        assert_eq!(
            session.add(&longer).expect_err("refused").status(),
            Status::Malformed
        );
        let mut longer = vector.mls_welcome.clone();
        longer.push(0x00);
        assert_eq!(
            joiner.join_welcome(&longer).expect_err("refused").status(),
            Status::Malformed
        );
        let mut longer = vector.mls_group_info.clone();
        longer.push(0x00);
        assert_eq!(
            joiner.join_external(&longer).expect_err("refused").status(),
            Status::Malformed
        );
        refusals += 3;

        // And a vector offered to the wrong door is refused on its kind, not on its bytes:
        // a welcome is not a group info and our seam must not confuse them.
        assert_eq!(
            joiner
                .join_external(&vector.mls_welcome)
                .expect_err("refused")
                .status(),
            Status::Malformed
        );
        assert_eq!(
            joiner
                .join_welcome(&vector.mls_group_info)
                .expect_err("refused")
                .status(),
            Status::Malformed
        );
        refusals += 2;
    }
    assert_eq!(refusals, 90, "the negative control ran the wrong count");
}

// MARK: crypto-basics.json

/// One entry of `crypto-basics.json`. The inner objects are read as raw JSON because each
/// has its own field set and naming them twice would only be a second place to be wrong.
#[derive(Deserialize)]
struct CryptoBasicsVector {
    cipher_suite: u16,
    derive_secret: serde_json::Value,
    derive_tree_secret: serde_json::Value,
    encrypt_with_label: serde_json::Value,
    expand_with_label: serde_json::Value,
    ref_hash: serde_json::Value,
    sign_with_label: serde_json::Value,
}

/// A hex field of one of those inner objects.
fn field(object: &serde_json::Value, name: &str) -> Vec<u8> {
    hex::decode(
        object[name]
            .as_str()
            .unwrap_or_else(|| panic!("{name} is a hex string")),
    )
    .unwrap_or_else(|error| panic!("{name}: {error}"))
}

/// A string field.
fn label(object: &serde_json::Value, name: &str) -> String {
    object[name]
        .as_str()
        .unwrap_or_else(|| panic!("{name} is a string"))
        .to_string()
}

/// RFC 9420's variable-length vector encoding, through the same `tls_codec` this crate
/// serialises messages with, so a wrong length prefix here would be the same wrong length
/// prefix on the wire.
fn variable(bytes: &[u8]) -> Vec<u8> {
    VLBytes::new(bytes.to_vec())
        .tls_serialize_detached()
        .expect("a variable-length vector")
}

/// RFC 9420 §8: `struct { uint16 length; opaque label<V>; opaque context<V>; } KDFLabel`,
/// where the label is the RFC's `"MLS 1.0 "` prefix followed by the caller's.
fn kdf_label(length: u16, name: &str, context: &[u8]) -> Vec<u8> {
    let mut encoded = length.to_be_bytes().to_vec();
    encoded.extend(variable(format!("MLS 1.0 {name}").as_bytes()));
    encoded.extend(variable(context));
    encoded
}

/// RFC 9420 §5.1 and §5.2: `struct { opaque label<V>; opaque content<V>; }`, which is both
/// `SignContent` and `EncryptContext` and, without the `"MLS 1.0 "` prefix, `RefHashInput`.
fn labelled(name: &str, content: &[u8]) -> Vec<u8> {
    let mut encoded = variable(name.as_bytes());
    encoded.extend(variable(content));
    encoded
}

#[test]
fn every_crypto_basics_construction_matches_through_the_provider_our_store_assembles() {
    let raw = corpus("crypto-basics.json");
    let all: Vec<CryptoBasicsVector> =
        serde_json::from_slice(&raw).expect("crypto-basics.json parses");
    assert_eq!(all.len(), 7, "the vendored crypto-basics.json changed size");
    let ours = u16::from(CIPHERSUITE);
    let mine: Vec<&CryptoBasicsVector> = all.iter().filter(|c| c.cipher_suite == ours).collect();
    // One entry per ciphersuite upstream, six of them for suites this build does not
    // implement. Skipped for the same reason as in `messages.json`: one ciphersuite.
    assert_eq!(mine.len(), 1);
    assert_eq!(all.len() - mine.len(), 6);

    // The provider is reached exactly the way `session.rs` reaches it, so this is the
    // assembly in `store.rs` under test and not a fresh `RustCrypto` built for the
    // occasion. A provider wired to the wrong crypto would pass every functional test in
    // this crate and fail here.
    let device = device("crypto-basics");
    let crypto = device.provider().crypto();
    let suite: Ciphersuite = CIPHERSUITE;
    let mut run = 0_usize;

    for vector in mine {
        // RefHash(label, value) = Hash(RefHashInput). The label carries no "MLS 1.0 "
        // prefix: in the RFC the callers pass the full string, as in
        // "MLS 1.0 KeyPackage Reference".
        let input = labelled(
            &label(&vector.ref_hash, "label"),
            &field(&vector.ref_hash, "value"),
        );
        assert_eq!(
            crypto.hash(suite.hash_algorithm(), &input).expect("a hash"),
            field(&vector.ref_hash, "out"),
            "ref_hash"
        );
        run += 1;

        // ExpandWithLabel(Secret, Label, Context, Length) = KDF.Expand(Secret, KDFLabel, Length).
        let length = vector.expand_with_label["length"]
            .as_u64()
            .expect("a length") as u16;
        let expanded = crypto
            .hkdf_expand(
                suite.hash_algorithm(),
                &field(&vector.expand_with_label, "secret"),
                &kdf_label(
                    length,
                    &label(&vector.expand_with_label, "label"),
                    &field(&vector.expand_with_label, "context"),
                ),
                usize::from(length),
            )
            .expect("an expansion");
        assert_eq!(
            expanded.as_slice(),
            field(&vector.expand_with_label, "out"),
            "expand_with_label"
        );
        run += 1;

        // DeriveSecret(Secret, Label) = ExpandWithLabel(Secret, Label, "", KDF.Nh).
        let nh = suite.hash_length();
        let derived = crypto
            .hkdf_expand(
                suite.hash_algorithm(),
                &field(&vector.derive_secret, "secret"),
                &kdf_label(nh as u16, &label(&vector.derive_secret, "label"), &[]),
                nh,
            )
            .expect("a derivation");
        assert_eq!(
            derived.as_slice(),
            field(&vector.derive_secret, "out"),
            "derive_secret"
        );
        run += 1;

        // DeriveTreeSecret(Secret, Label, Generation, Length), whose context is the
        // generation as a big-endian uint32.
        let length = vector.derive_tree_secret["length"]
            .as_u64()
            .expect("a length") as u16;
        let generation = vector.derive_tree_secret["generation"]
            .as_u64()
            .expect("a generation") as u32;
        let derived = crypto
            .hkdf_expand(
                suite.hash_algorithm(),
                &field(&vector.derive_tree_secret, "secret"),
                &kdf_label(
                    length,
                    &label(&vector.derive_tree_secret, "label"),
                    &generation.to_be_bytes(),
                ),
                usize::from(length),
            )
            .expect("a derivation");
        assert_eq!(
            derived.as_slice(),
            field(&vector.derive_tree_secret, "out"),
            "derive_tree_secret"
        );
        run += 1;

        // VerifyWithLabel(pub, label, content, signature) over SignContent. This is the
        // construction every credential in the group is authenticated with, so a provider
        // that got it wrong would accept nobody and be accepted by nobody.
        let content = labelled(
            &format!("MLS 1.0 {}", label(&vector.sign_with_label, "label")),
            &field(&vector.sign_with_label, "content"),
        );
        crypto
            .verify_signature(
                suite.signature_algorithm(),
                &content,
                &field(&vector.sign_with_label, "pub"),
                &field(&vector.sign_with_label, "signature"),
            )
            .expect("sign_with_label verifies");
        run += 1;

        // DecryptWithLabel(priv, label, context, kem_output, ciphertext) == plaintext.
        // The HPKE half of the provider, which is how a welcome's group secrets reach a
        // joiner, so `Device::join_welcome` rests on exactly this.
        let info = labelled(
            &format!("MLS 1.0 {}", label(&vector.encrypt_with_label, "label")),
            &field(&vector.encrypt_with_label, "context"),
        );
        let opened = crypto
            .hpke_open(
                HpkeConfig(
                    suite.hpke_kem_algorithm(),
                    suite.hpke_kdf_algorithm(),
                    suite.hpke_aead_algorithm(),
                ),
                &HpkeCiphertext {
                    kem_output: field(&vector.encrypt_with_label, "kem_output").into(),
                    ciphertext: field(&vector.encrypt_with_label, "ciphertext").into(),
                },
                &field(&vector.encrypt_with_label, "priv"),
                &info,
                &[],
            )
            .expect("encrypt_with_label opens");
        assert_eq!(
            opened,
            field(&vector.encrypt_with_label, "plaintext"),
            "encrypt_with_label"
        );
        run += 1;
    }

    // Six constructions, and `crypto-basics.json` defines exactly six.
    assert_eq!(run, 6, "the crypto suite ran the wrong count");
}

// MARK: welcome.json

/// One entry of `welcome.json`. `init_priv` and `signer_pub` are read and deliberately not
/// used: see the assertion below for why the seam cannot take them.
#[derive(Deserialize)]
struct WelcomeVector {
    cipher_suite: u16,
    #[serde(with = "hex::serde")]
    key_package: Vec<u8>,
    #[serde(with = "hex::serde")]
    welcome: Vec<u8>,
}

#[test]
fn the_welcome_vector_reaches_our_joiner_through_our_own_deserialiser() {
    let raw = corpus("welcome.json");
    let all: Vec<WelcomeVector> = serde_json::from_slice(&raw).expect("welcome.json parses");
    assert_eq!(all.len(), 7, "the vendored welcome.json changed size");
    let ours = u16::from(CIPHERSUITE);
    let mine: Vec<&WelcomeVector> = all.iter().filter(|w| w.cipher_suite == ours).collect();
    assert_eq!(mine.len(), 1);
    assert_eq!(all.len() - mine.len(), 6);

    let mut run = 0_usize;
    for vector in mine {
        // The vector's own joiner cannot be reconstructed here: it is identified by an
        // `init_priv` that would have to be installed in this device's key store, and
        // `Device` has no import path by design (`session::load_or_create_signer` mints
        // and keeps its own). So what is proved is the half that is ours: the welcome
        // decodes through `Device::join_welcome`'s deserialiser and reaches OpenMLS, which
        // then refuses it for the only correct reason, that this device holds no matching
        // key package.
        let joiner = device("welcome-vector");
        let refused = joiner
            .join_welcome(&vector.welcome)
            .expect_err("this device was never invited");
        assert_eq!(
            refused.status(),
            Status::Protocol,
            "a conformant welcome must fail past the decoder, not inside it"
        );
        run += 1;

        // The key package the welcome is addressed to, through `read_key_package`.
        let mut session = group();
        decoded(
            "welcome.json key_package through Session::add",
            status(session.add(&vector.key_package)),
        );
        run += 1;

        // And both re-encode to the bytes the generator wrote, which is the marshalling
        // claim itself.
        const HEADER: usize = 4;
        match MlsMessageIn::tls_deserialize_exact(&vector.welcome)
            .expect("a welcome")
            .extract()
        {
            MlsMessageBodyIn::Welcome(welcome) => assert_eq!(
                welcome.tls_serialize_detached().expect("re-encoded"),
                vector.welcome[HEADER..]
            ),
            other => panic!("welcome.json welcome is not a welcome: {other:?}"),
        }
        run += 1;
        match MlsMessageIn::tls_deserialize_exact(&vector.key_package)
            .expect("a key package")
            .extract()
        {
            MlsMessageBodyIn::KeyPackage(package) => assert_eq!(
                package.tls_serialize_detached().expect("re-encoded"),
                vector.key_package[HEADER..]
            ),
            other => panic!("welcome.json key_package is not a key package: {other:?}"),
        }
        run += 1;
    }
    assert_eq!(run, 4, "the welcome suite ran the wrong count");
}

// MARK: The count that makes a silent pass impossible

#[test]
fn this_suite_cannot_pass_by_running_nothing() {
    // The failure mode the whole file is designed against: a corpus that failed to load, a
    // filter that matched nothing, and a green suite that proved nothing. The individual
    // tests assert their own counts exactly; this one asserts the floor independently, off
    // the corpus itself, so a filter bug in one place cannot make every count agree on
    // zero.
    let (total, mine) = messages();
    assert_eq!(total, 300);
    assert!(
        mine.len() >= 100,
        "messages.json lost its ciphersuite-1 set"
    );

    let crypto: Vec<CryptoBasicsVector> =
        serde_json::from_slice(&corpus("crypto-basics.json")).expect("parses");
    let welcome: Vec<WelcomeVector> =
        serde_json::from_slice(&corpus("welcome.json")).expect("parses");
    let ours = u16::from(CIPHERSUITE);
    assert!(crypto.iter().any(|c| c.cipher_suite == ours));
    assert!(welcome.iter().any(|w| w.cipher_suite == ours));

    // 700 acceptances, 700 re-encodings, 100 length checks, 90 refusals, 6 constructions,
    // 4 welcome assertions. The number is written down so that a test quietly reduced to a
    // loop over nothing changes it.
    const MINIMUM_VECTOR_ASSERTIONS: usize = 700 + 700 + 100 + 90 + 6 + 4;
    assert_eq!(MINIMUM_VECTOR_ASSERTIONS, 1600);

    // And the ciphersuite this whole filter turns on is the one the seam declares, not a
    // literal repeated here. A build that changed ciphersuite would fail every count above
    // rather than silently test a suite it no longer speaks.
    assert_eq!(
        CIPHERSUITE,
        Ciphersuite::MLS_128_DHKEMX25519_AES128GCM_SHA256_Ed25519
    );
    assert_eq!(ours, 1);
}
