#!/usr/bin/env python3
"""The WAKE frame corpus, derived from the grammar rather than from a codec.

    scripts/push-vectors.py --check    the checked-in file is what this produces
    scripts/push-vectors.py --write    regenerate it

`specs/backend/contracts/wire/vectors/call-frames.json` is generated by the Swift
client and the relay checks itself against it, which is the right shape: two
independently written codecs that were never compared are two bugs waiting, and
vectors generated by the side under test prove nothing.

The WAKE frame could not be done that way, because it was specified before either
codec existed and a corpus written by whichever arrived first would have ratified
whatever that one happened to do. So these bytes come from a third place: this
file, which encodes deterministic CBOR by hand from the WakeFrame production in
`../specs/backend/contracts/wire/wire.cddl`, with no CBOR library on purpose. It
is checked in as a script rather than left in a scratch directory because a
hand-computed corpus nobody can re-derive is a corpus that rots the first time
somebody edits a vector to make a red test go green, and a wrong vector is worse
than a missing one.

When either implementation grows its own generator, this stays: three sources
agreeing is strictly better than two, and this is the only one of the three that
is not also a thing under test.
"""
import argparse
import json
import sys

WAKE_TAG = 25
# Deliberately absurd, and the reason is the one thing a byte corpus cannot fix any
# other way: expires_at is refused when it is already past, so an accepting vector
# with a plausible expiry is an accepting vector that becomes a rejecting one on a
# Tuesday. 2100-01-01. The rejecting vector below carries a real elapsed date, which
# is the direction that stays true forever.
E = 4102444800000          # ms since epoch, 2100-01-01T00:00:00Z
E_PAST = 1000000000000     # ms since epoch, 2001-09-09T01:46:40Z, elapsed forever
U64_MAX = 18446744073709551615
H16 = bytes.fromhex("7f3a9c1d5e2b48a06c91d4f7e3b8a25c")
URL = "https://ringer.weald.team/v1/handles"


def head(major: int, value: int) -> bytes:
    mt = major << 5
    if value < 24:
        return bytes([mt | value])
    if value < 0x100:
        return bytes([mt | 24, value])
    if value < 0x10000:
        return bytes([mt | 25]) + value.to_bytes(2, "big")
    if value < 0x100000000:
        return bytes([mt | 26]) + value.to_bytes(4, "big")
    return bytes([mt | 27]) + value.to_bytes(8, "big")


def uint(v: int) -> bytes:
    return head(0, v)


def bstr(b: bytes) -> bytes:
    return head(2, len(b)) + b


def tstr(s: str) -> bytes:
    raw = s.encode()
    return head(3, len(raw)) + raw


def arr(items) -> bytes:
    return head(4, len(items)) + b"".join(items)


def emap(pairs) -> bytes:
    return head(5, len(pairs)) + b"".join(k + v for k, v in pairs)


TRUE = b"\xf5"
FALSE = b"\xf4"


def wake(form_bytes: bytes, fields: bytes) -> bytes:
    """[25, [form, fields]] with the two arrays definite and two long."""
    return head(4, 2) + uint(WAKE_TAG) + head(4, 2) + form_bytes + fields


def register(handle: bytes, categories: bytes, expires: bytes) -> bytes:
    return wake(uint(1), head(4, 3) + bstr(handle) + categories + expires)


V = []


def add(name, form, raw, expect, reason, fields, code=None):
    V.append({
        "name": name,
        "id": name,
        "form": form,
        "tag": WAKE_TAG,
        "expect": expect,
        "code": code,
        "reason": reason,
        "note": reason,
        "fields": fields,
        "hex": raw.hex(),
        "encoded": raw.hex(),
        "bytes": len(raw),
    })


# --------------------------------------------------------------- accepting
add("wake-register-message-only", 1,
    register(H16, uint(1), uint(E)), "accept",
    "Form 1, the canonical registration: a 16 byte handle, the message bit alone, "
    "and an expiry the relay will forget the row at. The frame carries no device "
    "identifier because the relay learns the principal from the authenticated "
    "session rather than from a field. The expiry is the year 2100 in every "
    "accepting vector here, which is not a realistic registration and is not meant "
    "to be: an elapsed expires_at is a refusal, so a corpus with a plausible date in "
    "it is a corpus that starts failing on a Tuesday.",
    {"handle": H16.hex(), "categories": 1, "expires_at": E})

add("wake-register-call-only", 1,
    register(H16, uint(2), uint(E)), "accept",
    "The call bit alone. A device that wants to be rung and not otherwise "
    "disturbed is the one registration shape that has to work on a locked phone, "
    "and the relay masks every other category out rather than sending and letting "
    "the client ignore it.",
    {"handle": H16.hex(), "categories": 2, "expires_at": E})

add("wake-register-handshake-only", 1,
    register(H16, uint(4), uint(E)), "accept",
    "The handshake bit alone, which is the top defined bit. Present so the "
    "boundary between the last defined bit and the first undefined one is covered "
    "from both sides.",
    {"handle": H16.hex(), "categories": 4, "expires_at": E})

add("wake-register-all-three", 1,
    register(H16, uint(7), uint(E)), "accept",
    "Every defined bit set, which is the ordinary shape of a phone that wants "
    "messages, calls and handshakes. 7 is the largest legal mask and 8 is the "
    "first illegal one.",
    {"handle": H16.hex(), "categories": 7, "expires_at": E})

add("wake-register-expires-at-width-ceiling", 1,
    register(H16, uint(1), uint(U64_MAX)), "accept",
    "expires_at at the ceiling of its width. CBOR encodes 2^64-1 in nine bytes "
    "and both sides must read it as a number rather than saturating it. The relay "
    "refuses an expiry already in the past and has nothing to say about one "
    "absurdly far in the future, because the GC pass is what collects the row and "
    "a ringer that mints a century is a ringer nobody has to defend against.",
    {"handle": H16.hex(), "categories": 1, "expires_at": U64_MAX})

add("wake-registered", 2,
    wake(uint(2), arr([uint(E)])), "accept",
    "Form 2, the relay's answer to a registration: the one expiry the relay will "
    "actually honour, which is the client's own value and is echoed rather than "
    "assumed so a client never has to guess when its registration lapses.",
    {"expires_at": E})

add("wake-clear", 3,
    wake(uint(3), arr([])), "accept",
    "Form 3. No fields at all: the row is keyed on the workspace and the "
    "authenticated principal, so there is nothing for the client to name and "
    "nothing it could name that the relay would trust.",
    {})

add("wake-cleared", 4,
    wake(uint(4), arr([])), "accept",
    "Form 4. Answered identically whether a row existed or not, because a "
    "distinguishable answer would make this frame an oracle for whether a "
    "principal holds a registration.",
    {})

add("wake-query", 5,
    wake(uint(5), arr([])), "accept",
    "Form 5. The frame that makes a self-hosted deployment work with a shipped "
    "client: the device does not know which ringer to register with and must not "
    "guess, because guessing ours would register a self-hoster's users with a "
    "ringer their operator did not choose.",
    {})

add("wake-capability-on", 6,
    wake(uint(6), arr([TRUE, tstr(URL)])), "accept",
    "Form 6 with push configured. The relay states the ringer rather than the "
    "client assuming one. Asked over this frame and never at CONNECT_ACK time, "
    "because adding a field to CONNECT_ACK is the one thing a version "
    "negotiation must not require.",
    {"enabled": True, "register_url": URL})

add("wake-capability-off", 6,
    wake(uint(6), arr([FALSE, tstr("")])), "accept",
    "Form 6 with push off, which is the default and a supported deployment "
    "rather than a degraded one. The empty url is legal and load bearing: a "
    "client reading enabled false holds no registration and raises no "
    "expectation of push, so there is nothing for a url to mean.",
    {"enabled": False, "register_url": ""})

url512 = "https://ringer.weald.team/v1/handles?p=" + "a" * (512 - len("https://ringer.weald.team/v1/handles?p="))
assert len(url512) == 512
add("wake-capability-url-at-ceiling", 6,
    wake(uint(6), arr([TRUE, tstr(url512)])), "accept",
    "A register_url of exactly 512 bytes. The boundary is inclusive, as it is "
    "for every other ceiling in this protocol: a bound a client cannot reach is "
    "a bound it cannot plan against. The vector one byte over is below.",
    {"enabled": True, "register_url": url512})

# --------------------------------------------------------------- rejecting
add("wake-reject-handle-fifteen-bytes", 1,
    register(H16[:15], uint(1), uint(E)), "reject",
    "A 15 byte handle. reject/push_handle_malformed, and a reject rather than a "
    "denial because a wrong-length handle is permanently wrong as sent and "
    "resending it would be wrong in the same way.",
    {"handle": H16[:15].hex(), "categories": 1, "expires_at": E},
    "reject/push_handle_malformed")

add("wake-reject-handle-seventeen-bytes", 1,
    register(H16 + b"\xaa", uint(1), uint(E)), "reject",
    "A 17 byte handle. The other side of the same boundary, present because a "
    "length check written as a minimum passes this and a length check written as "
    "a maximum passes the vector above it.",
    {"handle": (H16 + b"\xaa").hex(), "categories": 1, "expires_at": E},
    "reject/push_handle_malformed")

add("wake-reject-categories-zero", 1,
    register(H16, uint(0), uint(E)), "reject",
    "An empty bitmask. At least one bit must be set: a registration that admits "
    "no category is a row that can never produce a wake, and storing one would "
    "leave a device believing it had registered for something.",
    {"handle": H16.hex(), "categories": 0, "expires_at": E},
    "reject/push_handle_malformed")

add("wake-reject-categories-undefined-bit", 1,
    register(H16, uint(9), uint(E)), "reject",
    "Bit 8 set alongside the message bit. The category set is closed at three "
    "values and an undefined bit is refused rather than masked away, so a future "
    "client cannot widen what a wake means without a version bump.",
    {"handle": H16.hex(), "categories": 9, "expires_at": E},
    "reject/push_handle_malformed")

add("wake-reject-categories-only-undefined-bit", 1,
    register(H16, uint(8), uint(E)), "reject",
    "Bit 8 alone. Refused by the undefined-bit rule and not by the empty-mask "
    "rule, and the pair matters: an implementation that only checked for zero "
    "would accept this and hold a registration admitting nothing it can name.",
    {"handle": H16.hex(), "categories": 8, "expires_at": E},
    "reject/push_handle_malformed")

add("wake-reject-expires-at-not-a-uint", 1,
    register(H16, uint(1), tstr(str(E))), "reject",
    "expires_at as a text string carrying the same digits. reject/malformed_header "
    "rather than the push code, because the field is not of its declared type and "
    "the codec refuses it before the push path is reached, exactly as it refuses a "
    "wrong-length content hash.",
    {"handle": H16.hex(), "categories": 1, "expires_at": str(E)},
    "reject/malformed_header")

add("wake-reject-expires-at-already-past", 1,
    register(H16, uint(1), uint(E_PAST)), "reject",
    "A well-formed expiry that has already elapsed. Refused rather than stored "
    "and immediately collected, because a row the GC pass would remove on its "
    "next sweep is a registration the device would spend a week believing in.",
    {"handle": H16.hex(), "categories": 1, "expires_at": E_PAST},
    "reject/push_handle_malformed")

add("wake-reject-register-url-not-https", 6,
    wake(uint(6), arr([TRUE, tstr("http://ringer.weald.team/v1/handles")])), "reject",
    "A plaintext register_url. Refused by the client, which is the direction "
    "this form travels: a device that registered over http would hand its APNs "
    "token to whatever answered, and the whole design is built on the token "
    "reaching exactly one party.",
    {"enabled": True, "register_url": "http://ringer.weald.team/v1/handles"},
    "reject/push_handle_malformed")

url513 = url512 + "a"
add("wake-reject-register-url-513-bytes", 6,
    wake(uint(6), arr([TRUE, tstr(url513)])), "reject",
    "One byte past the 512 byte ceiling. Refused on the declared length, so the "
    "vector immediately above it and this one differ by exactly the byte the "
    "check is about.",
    {"enabled": True, "register_url": url513},
    "reject/push_handle_malformed")

indefinite_handle = (
    head(4, 2) + uint(WAKE_TAG) + head(4, 2) + uint(1)
    + head(4, 3) + b"\x5f" + bstr(H16) + b"\xff" + uint(1) + uint(E)
)
add("wake-reject-indefinite-length-handle", 1,
    indefinite_handle, "reject",
    "The handle as an indefinite-length byte string whose single chunk is the "
    "same 16 bytes. Deterministic CBOR is a validation rule and not a "
    "convention, so this is refused even though it decodes to a handle the relay "
    "would otherwise have stored.",
    {"handle": H16.hex(), "categories": 1, "expires_at": E},
    "reject/noncanonical_cbor")

nonshortest = (
    head(4, 2) + uint(WAKE_TAG) + head(4, 2) + uint(1)
    + head(4, 3) + bstr(H16) + b"\x18\x01" + uint(E)
)
add("wake-reject-nonshortest-categories", 1,
    nonshortest, "reject",
    "categories 1 encoded as a two-byte uint. Refused for the reason every other "
    "non-shortest integer in this protocol is: an encoder artifact must not be "
    "able to produce two byte strings that mean one frame.",
    {"handle": H16.hex(), "categories": 1, "expires_at": E},
    "reject/noncanonical_cbor")

map_for_array = head(4, 2) + uint(WAKE_TAG) + head(4, 2) + uint(3) + emap([])
add("wake-reject-map-where-an-array-is-required", 3,
    map_for_array, "reject",
    "A Clear whose wake-fields is an empty map rather than an empty array. The "
    "grammar says array everywhere and the two encode differently, so a decoder "
    "loose enough to take either is a decoder two implementations can disagree "
    "inside.",
    {},
    "reject/malformed_header")

trailing = wake(uint(5), arr([])) + b"\x00"
add("wake-reject-trailing-byte", 5,
    trailing, "reject",
    "A complete Query followed by one extra byte. A frame is exactly one CBOR "
    "item and nothing after it, so trailing data is refused rather than ignored: "
    "a decoder that stops at the end of the item leaves an attacker a byte of "
    "channel nobody is validating.",
    {},
    "reject/noncanonical_cbor")

oversize = (
    head(4, 2) + uint(WAKE_TAG) + head(4, 2) + uint(1)
    + head(4, 4) + bstr(H16) + uint(1) + uint(E) + bstr(b"\x5a" * 1000)
)
assert len(oversize) > 1024
add("wake-reject-over-the-frame-ceiling", 1,
    oversize, "reject",
    f"{len(oversize)} bytes, past the 1 KiB WAKE ceiling. Refused on the declared "
    "frame length before the body is decoded, so the fourth element is never "
    "reached and the refusal names the frame ceiling rather than the arity it "
    "would otherwise have complained about.",
    {"handle": H16.hex(), "categories": 1, "expires_at": E, "padding": "fill:5a:1000"},
    "reject/envelope_too_large")

add("wake-reject-unknown-form", 7,
    wake(uint(7), arr([])), "reject",
    "Form 7. The form set is closed at six and an unrecognised value is refused "
    "rather than carried, which is the same rule the closed call-kind set has and "
    "for the same reason: routing semantics do not change without a version bump.",
    {},
    "reject/malformed_header")

add("wake-reject-register-wrong-arity", 1,
    wake(uint(1), head(4, 2) + bstr(H16) + uint(1)), "reject",
    "A Register carrying two fields instead of three. Refused on arity rather "
    "than defaulted, because a missing expires_at defaulted to anything would be "
    "the relay choosing how long a wake capability lives.",
    {"handle": H16.hex(), "categories": 1},
    "reject/malformed_header")

out = {
    "$comment": (
        "The WAKE frame corpus, protocol version 4. Computed by hand from the "
        "WakeFrame production in ../wire.cddl rather than by either implementation's "
        "encoder, because vectors generated by a side under test prove nothing and "
        "there was no second codec to generate them from when this frame was "
        "specified. The relay checks itself against these bytes and so does the "
        "client; the first of them to grow a generator must reproduce this file byte "
        "for byte, exactly as scripts/call-vectors.sh does for call-frames.json. "
        "`fields` writes each frame out in its own field order so the hex is "
        "checkable by hand. `hex` and `encoded` are the same string under both names, "
        "and `name`/`id` and `reason`/`note` are the same pair, so a reader written "
        "against this file and one written against call-frames.json both work."
    ),
    "note": (
        "Generated from specs/backend/contracts/wire/wire.cddl. Deterministic CBOR, "
        "definite length, shortest-form integers, no tags and no floats. Registered "
        "in manifest.json, which carries the relay-state vectors for the four push "
        "error codes that no byte string can express."
    ),
    "protocol_version": 4,
    "wake_protocol_version": 4,
    "max_wake_frame_bytes": 1024,
    "max_register_url_bytes": 512,
    "handle_bytes": 16,
    "categories": {"message": 1, "call": 2, "handshake": 4},
    "vectors": V,
}

import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PATH = os.path.join(ROOT, "specs/backend/contracts/wire/vectors/push-frames.json")
RENDERED = json.dumps(out, indent=2) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="fail if the checked-in file is not what this produces")
    parser.add_argument("--write", action="store_true", help="regenerate the file")
    args = parser.parse_args()

    if args.write:
        with open(PATH, "w") as fh:
            fh.write(RENDERED)
        print("wrote %s, %d vectors" % (PATH, len(V)))
        for v in V:
            print("  %-7s %5d  %s" % (v["expect"], v["bytes"], v["name"]))
        return 0

    if args.check:
        try:
            held = open(PATH).read()
        except FileNotFoundError:
            print("no corpus at %s" % PATH, file=sys.stderr)
            return 1
        if held != RENDERED:
            print("the checked-in corpus is not what the grammar produces. "
                  "Re-derive it with --write, or fix the grammar this reads from; "
                  "do not edit a vector to make a test pass.", file=sys.stderr)
            return 1
        accepts = sum(1 for v in V if v["expect"] == "accept")
        print("push-vectors: OK. %d vectors, %d accepting and %d rejecting, "
              "byte-identical to the corpus." % (len(V), accepts, len(V) - accepts))
        return 0

    parser.print_help()
    return 64


if __name__ == "__main__":
    sys.exit(main())
