-- The access set, and nothing else the relay could learn from it.
--
-- specs/backend/relay/wire.md, "The access set": the relay gets exactly one
-- piece of derived membership data. A set of salted principal hashes, the
-- device keys allowed to rotate that set, the recovery principals allowed one
-- narrow transition, and the chain that links each published version to the one
-- before it.
--
-- What the relay learns from these tables, stated so it can be checked against
-- the dump the step 6 gate takes: how many principals a workspace has, when that
-- number changes, and which presented device keys may rotate connection access.
-- There is no pubkey in `relay_access_entry` and there cannot be: an entry is
-- BLAKE3(pubkey || workspace_salt) and the relay hashes what a device presents at
-- AUTH in order to test membership. `authorizers` and `recovery` are clear keys
-- because the relay verifies their signatures, which is the one thing hashes
-- cannot do.

-- One salt per workspace, relay-held.
--
-- It hides nothing from the relay and is not there to: the relay must hash a
-- presented key to test membership, so it must hold the salt. It exists so a
-- stolen access set is not linkable against key material seen in another
-- workspace, in a backup, or in a leak.
create table if not exists relay_workspace (
    workspace_id text        primary key,
    -- 32 bytes, generated by the relay on first publication and never rotated:
    -- rotating it would invalidate every entry hash in the chain at once.
    salt         bytea       not null,
    created_at   timestamptz not null default now(),
    constraint relay_workspace_salt_is_32_bytes check (octet_length(salt) = 32)
);

-- One row per accepted publication. The chain, kept whole.
--
-- Kept whole rather than replaced, because the implicit-void rule in wire.md
-- needs history: "a grant is void once an accepted access set has contained the
-- joiner's hash and a later accepted set does not". A relay that stored only the
-- current set could not tell a set that never caught up with a new joiner, which
-- must not void the grant, from one that deliberately dropped a principal it
-- previously carried, which must.
create table if not exists relay_access_set (
    workspace_id text        not null references relay_workspace (workspace_id) on delete restrict,
    -- Exactly the previous version plus one. Enforced in the same transaction
    -- that inserts, so two concurrent publications cannot both win.
    version      bigint      not null,
    -- BLAKE3 over the canonical encoding with `sig` and the quorum signatures
    -- omitted: the set digest that the authorizer signed.
    digest       bytea       not null,
    -- The accepted previous set's digest. All zero at genesis.
    prev_hash    bytea       not null,
    -- The client's clock, carried and never trusted for anything the relay
    -- decides. Every expiry the relay owns is evaluated against `accepted_at`.
    issued_at    bigint      not null,
    -- The key that signed it, and whether it signed as an authorizer or under
    -- the narrow recovery rotation. Recorded because the probation rule below
    -- depends on which one it was.
    signer       bytea       not null,
    signed_as    text        not null,
    -- The frame as it arrived, byte for byte. A publication is evidence and the
    -- membership transparency log quotes it; re-encoding it here would make the
    -- signature uncheckable by anyone reading the table.
    body         bytea       not null,
    accepted_at  timestamptz not null default now(),
    primary key (workspace_id, version),
    constraint relay_access_set_digest_is_32_bytes check (octet_length(digest) = 32),
    constraint relay_access_set_prev_is_32_bytes check (octet_length(prev_hash) = 32),
    constraint relay_access_set_signer_is_32_bytes check (octet_length(signer) = 32),
    constraint relay_access_set_signed_as_known check (signed_as in ('authorizer', 'recovery')),
    -- A version is a count from zero. Constrained here rather than range-checked
    -- in the reader, so the reader has one path and not a second one that could
    -- only be reached by a row this constraint forbids.
    constraint relay_access_set_version_not_negative check (version >= 0)
);

create unique index if not exists relay_access_set_digest_idx
    on relay_access_set (workspace_id, digest);

-- The entries of one published version. Salted hashes, and nothing else.
create table if not exists relay_access_entry (
    workspace_id text   not null,
    version      bigint not null,
    entry_hash   bytea  not null,
    primary key (workspace_id, version, entry_hash),
    foreign key (workspace_id, version)
        references relay_access_set (workspace_id, version) on delete cascade,
    constraint relay_access_entry_is_32_bytes check (octet_length(entry_hash) = 32)
);

-- The connect check reads this on every AUTH, so it is indexed for the question
-- it is asked: is this hash in the newest version of this workspace's chain.
create index if not exists relay_access_entry_lookup_idx
    on relay_access_entry (workspace_id, entry_hash, version desc);

-- Authorizers and recovery principals, as clear keys, because the relay verifies
-- signatures by them. `role` rather than two tables: the two lists are read
-- together on every publication and a join of two tables to answer one question
-- is two indexes to keep in step.
create table if not exists relay_access_principal (
    workspace_id text   not null,
    version      bigint not null,
    role         text   not null,
    pubkey       bytea  not null,
    primary key (workspace_id, version, role, pubkey),
    foreign key (workspace_id, version)
        references relay_access_set (workspace_id, version) on delete cascade,
    constraint relay_access_principal_key_is_32_bytes check (octet_length(pubkey) = 32),
    constraint relay_access_principal_role_known
        check (role in ('authorizer', 'recovery', 'quorum'))
);

-- The recovery quorum's threshold, when one is registered. The keys themselves
-- are rows above with role 'quorum'.
create table if not exists relay_access_quorum (
    workspace_id text   not null,
    version      bigint not null,
    threshold    smallint not null,
    primary key (workspace_id, version),
    foreign key (workspace_id, version)
        references relay_access_set (workspace_id, version) on delete cascade,
    -- Between 1 and 255: the wire carries the threshold as one byte, so a row
    -- outside that range could not be re-encoded and the reader would need a
    -- branch for a state the wire cannot express.
    constraint relay_access_quorum_threshold_in_byte_range
        check (threshold >= 1 and threshold <= 255)
);

-- A device an authorizer became through a recovery rotation, and what it is
-- licensed to remove until a pre-existing authorizer or a quorum confirms it.
--
-- Rows are never deleted, only cleared. The transparency log names the rotation
-- that created a probation and the publication that cleared it, and a row that
-- vanished on clearing would take that history with it.
create table if not exists relay_access_probation (
    workspace_id     text        not null references relay_workspace (workspace_id) on delete restrict,
    -- The replacement device, as a clear key: it is an authorizer, so the relay
    -- verifies its signatures.
    device           bytea       not null,
    -- The version whose rotation introduced it. Every authorizer that predates
    -- this version can clear the probation.
    introduced_at    bigint      not null,
    -- The entries this device may remove while probationary, pinned by the
    -- rotation. May be empty.
    pending          bytea[]     not null default '{}',
    cleared_version  bigint,
    created_at       timestamptz not null default now(),
    cleared_at       timestamptz,
    primary key (workspace_id, device),
    constraint relay_access_probation_device_is_32_bytes check (octet_length(device) = 32),
    constraint relay_access_probation_version_not_negative check (introduced_at >= 0)
);

-- Rate limit for the narrow recovery transition: at most one per recovery
-- principal per 24 hours (wire.md). Held separately from the set chain because a
-- refused rotation must still count against the limit, and a refused publication
-- writes no version.
create table if not exists relay_recovery_rotation (
    workspace_id text        not null references relay_workspace (workspace_id) on delete restrict,
    recovery_key bytea       not null,
    -- Relay-observed. A client-supplied time here would make the limit advisory.
    attempted_at timestamptz not null default now(),
    primary key (workspace_id, recovery_key, attempted_at),
    constraint relay_recovery_rotation_key_is_32_bytes check (octet_length(recovery_key) = 32)
);

create index if not exists relay_recovery_rotation_recent_idx
    on relay_recovery_rotation (workspace_id, recovery_key, attempted_at desc);

-- A joiner's connection credential before any access set names them.
--
-- specs/backend/relay/wire.md, "Provisional grants and how they end": bounded at
-- birth by the invite's expiry, voided explicitly by a revocation tombstone, and
-- voided implicitly once an accepted set has carried the hash and a later
-- accepted set does not. `voided_reason` records which, because "why did that
-- socket close" is the first question an operator asks.
create table if not exists relay_provisional_grant (
    workspace_id  text        not null references relay_workspace (workspace_id) on delete restrict,
    -- The salted hash of the joiner's device, recorded on the invite reservation.
    -- A hash and not a key, so a grant carries no more than an entry does.
    device_hash   bytea       not null,
    -- The invite's expiry, in relay time. A grant is never renewable and cannot
    -- outlive its invite.
    expires_at    timestamptz not null,
    -- Set once an accepted set has carried this hash, so the implicit rule can
    -- tell "never caught up" from "deliberately dropped".
    seen_version  bigint,
    voided_at     timestamptz,
    voided_reason text,
    created_at    timestamptz not null default now(),
    primary key (workspace_id, device_hash),
    constraint relay_provisional_grant_hash_is_32_bytes check (octet_length(device_hash) = 32),
    constraint relay_provisional_grant_reason_known
        check (voided_reason is null or voided_reason in ('revoked', 'superseded', 'expired'))
);

create index if not exists relay_provisional_grant_live_idx
    on relay_provisional_grant (workspace_id, device_hash) where voided_at is null;
